# -*- coding: utf-8 -*-
"""EXTRACTED topics for batch06 (97 projects) — see build_batch01_topics_data.py
for the pattern and docs/topic_normalization_pipeline.md for the methodology.
"""

EXTRACTED_BATCH06 = {
"824": [
    ("Transformación del paisaje periurbano en ciudades intermedias: Cajamarca 2007-2017",
     "Analiza la transformación del paisaje periurbano de Cajamarca para contribuir a la gestión local sostenible, los derechos económicos, sociales y culturales de actores vulnerables, y la gobernanza democrática del territorio.",
     "Contribuir a la protección, la promoción y el ejercicio de los derechos económicos, sociales y culturales de los actores locales... de la gestión democrática e intercultural de su territorio", 0.88),
],
"1": [
    ("Zonificación de tejidos urbanos homogéneos en la periferia de Lima-Callao",
     "Propone zonificar la periferia de Lima-Callao en unidades morfológicas homogéneas (tejidos urbanos) más allá de las divisiones distritales, para orientar políticas de desarrollo urbano integral.",
     "definir unidades morfológicas de manera articulada e integral, zonificando espacios homogéneos (tejidos urbanos), más allá de las divisiones distritales", 0.88),
],
"393": [
    ("Interacción transectorial para la seguridad hídrica y resiliencia climática en Santa Eulalia",
     "Busca mejorar la gobernanza del agua en el Perú mediante el fortalecimiento de capacidades técnicas e institucionales para la seguridad hídrica y resiliencia al cambio climático en la subcuenca de Santa Eulalia.",
     "contribuir a una mejor gobernanza del agua en Perú... la mejora de la interacción transectorial es una estrategia efectiva para lograr la seguridad hídrica y el desarrollo de resiliencia al cambio climático", 0.85),
],
"2": [
    ("Vulnerabilidad de cultivos y agrobiodiversidad frente al cambio climático en Piura",
     "Analiza la vulnerabilidad de la producción de cultivos y la agrobiodiversidad frente al cambio climático en la región costera de Piura.",
     "Agrobiodiversidad; Cambio climático; Cultivos; Piura", 0.65),
],
"467": [
    ("Fases geométricas y complementariedad en polarimetría cuántica de un fotón",
     "Mide fases geométricas de fotones individuales evolucionando en trayectorias no geodésicas sobre la esfera de Poincaré, y estudia la desigualdad entre grado de polarización e indistinguibilidad mediante entrelazamiento polarización-camino.",
     "We report polarimetric measurements of geometric phases that are generated by evolving polarized photons along nongeodesic trajectories on the Poincaré sphere... only by entangling polarization and path (momentum)... can such an inequality represent a constraint", 0.9),
],
"36": [
    ("Ocultaciones astronómicas para astrometría del sistema solar",
     "Observa ocultaciones astronómicas como técnica de astrometría para el estudio de cuerpos del sistema solar.",
     "Astronomía Observacional; Ocultaciones Astronómicas; Astrometría; Sistema Solar", 0.62),
],
"442": [
    ("Cuantificación de biotoxinas lipofílicas marinas en moluscos bivalvos",
     "Cuantifica biotoxinas lipofílicas marinas en moluscos bivalvos y microalgas mediante cromatografía líquida acoplada a masas, para garantizar la seguridad alimentaria.",
     "Biotoxinas marinas; Moluscos bivalvos; Cromatografía líquida; Seguridad alimentaria", 0.7),
],
"760": [
    ("Webs holomorfos e hipersuperficies Levi-flat con singularidades",
     "Caracteriza webs holomorfos que dejan invariante una hipersuperficie Levi-flat real-analítica con singularidades, estudiando la foliación asociada en la variedad de incidencia; demuestra existencia de singularidades dicríticas.",
     "caracterizar los webs holomorfos que dejan invariante una hipersuperficie real analítica Levi-flat en espacios afines y proyectivos... We give some hypotheses to guarantee the existence of dicritical singularities", 0.9),
],
"904": [
    ("Desempeño de módulos fotovoltaicos bifaciales bajo el clima de Lima",
     "Investiga el desempeño eléctrico de módulos fotovoltaicos bifaciales bajo el clima nublado limeño, comparando dos orientaciones y registrando variables meteorológicas para predecir su producción energética.",
     "se investigará el desempeño de dos distintas tecnologías y dos diferentes configuraciones de módulos FV bifaciales... aplicarán y compararán dos configuraciones de orientaciones", 0.92),
],
"675": [
    ("Arqueometría de la composición química de las monedas de Sol de plata (1863-1935)",
     "Estudia mediante XRF y EDX no destructivos la composición de aleaciones de plata de las monedas de Sol peruanas entre 1863 y 1935, buscando evidencia de devaluación monetaria asociada a crisis económicas.",
     "estudiar la composición química de las aleaciones de plata usadas para la acuñación de las diferentes monedas de Sol... la posibilidad de encontrar fenómenos similares a los observados en otras partes del mundo", 0.92),
],
"423": [
    ("Clasificación analítico-topológica de gérmenes de foliaciones en dimensión 2 y 3",
     "Estudia la dinámica local de gérmenes de foliaciones o campos analíticos cerca de una singularidad en sistemas de dimensión 2 y 3, aportando a su clasificación analítico-topológica.",
     "el estudio de la dinámica local de un germen de foliación o campo analítico en las cercanías de una singularidad... realizar un aporte a la clasificación analítico-topológica", 0.85),
],
"372": [
    ("Perfil químico multivariable de café y cacao peruano por RMN y masas",
     "Caracteriza el perfil químico del café y cacao peruano mediante análisis multivariable de resonancia magnética nuclear y espectrometría de masas.",
     "El café y el cacao peruano son productos muy apreciados a nivel mundial por las propiedades únicas que poseen, resultado del clima privilegiado", 0.78),
],
"494": [
    ("Protocolo LIBS para determinar la calidad y el carbono de suelos",
     "Desarrolla un protocolo de espectroscopia de plasma inducido por láser (LIBS) para clasificar la calidad de suelos según su origen y cuantificar carbono y pH en suelos agrícolas.",
     "identificar los elementos químicos presentes en los suelos, y luego usar esta información para establecer un protocolo de medición que permita clasificar la calidad de suelos", 0.9),
],
"659": [
    ("Principio de grandes desviaciones para un modelo de reacción-difusión estocástico",
     "Establece el principio de grandes desviaciones para la medida estacionaria de un proceso que superpone exclusión simple simétrica (Kawasaki) y dinámica spin-flip (Glauber), deduciendo la concentración en soluciones estacionarias estables de la ecuación hidrodinámica.",
     "We prove the large deviations principle for the empirical measure under the stationary state... the stationary state is concentrated on the stationary solutions of the hydrodynamic equation which are stable", 0.88),
],
"498": [
    ("Singularidades de foliaciones holomorfas de codimensión uno nilpotentes",
     "Estudia foliaciones holomorfas de codimensión uno nilpotentes en (C3,0) cuando la superficie invariante no es del tipo superficie generalizada, caracterizando sus singularidades dicríticas y de silla-nodo.",
     "complementaremos este estudio en el caso que la foliación no es superficie generalizada, este tipo de foliaciones admiten las singularidades mas complicadas... dicriticas y sillas nodos", 0.88),
],
"898": [
    ("Rendimiento y degradación de tecnologías fotovoltaicas emergentes con IA y plataforma pública",
     "Amplía el monitoreo de sistemas fotovoltaicos conectados a red en seis universidades peruanas de distintas zonas climáticas, desarrollando un sistema IoT, modelos de inteligencia artificial y una plataforma pública en línea para evaluar rendimiento y degradación de tecnologías emergentes.",
     "acrecentará y universalizará el impacto del proyecto base en el que se han instalado sistemas fotovoltaicos conectados a red (SFCR) en seis universidades peruanas... plataforma informática online... con un módulo de inteligencia artificial para la predicción de rendimiento energético", 0.9),
],
"39": [
    ("Modelos de regresión Beta y alternativos para datos proporcionales",
     "Propone nuevos modelos de regresión (clásicos y bayesianos) para variables continuas acotadas al intervalo (0,1), como proporciones y tasas, superando las limitaciones de la distribución Beta estándar.",
     "Una clase de distribuciones que permite modelar variables continuas limitadas al intervalo (0,1) es la distribución Beta... implementar estas distribuciones u otras existentes en la literatura en un modelo de regresión alternativo", 0.88),
],
"849": [
    ("Dopaje con terbio en películas conductoras transparentes ITO y AZO",
     "Investiga cómo el dopaje con terbio afecta las propiedades ópticas, eléctricas y de luminiscencia de películas delgadas de ITO y AZO fabricadas por pulverización catódica de radiofrecuencia, bajo distintas condiciones de recocido.",
     "The effect of terbium doping on the optical, electrical and light emission properties of sputtered indium tin oxide and aluminum doped zinc oxide thin films will be investigated for different annealing conditions", 0.88),
],
"9": [
    ("Construcción y estudio de soluciones de ecuaciones algebraicas y diferenciales",
     "Estudia la construcción y clasificación de soluciones de ecuaciones algebraicas y diferenciales mediante nuevos métodos de resolución.",
     "El objetivo central de nuestro proyecto es la construcción y estudio de las soluciones de ecuaciones algebraicas y diferenciales", 0.75),
],
"775": [
    ("Modulación metabólica del secado postcosecha de la maca para enriquecimiento nutracéutico",
     "Estudia los procesos metabólicos del secado postcosecha de la maca para modular su composición química y enriquecerla en amidas y otros compuestos nutracéuticos.",
     "mejorar el conocimiento sobre los procesos metabólicos del secado postcosecha que permitan modular los factores que determinan la composición química... de la harina de maca", 0.85),
],
"517": [
    ("Hidrogeles conmutables con nanopartículas de oro sensibles a temperatura y pH",
     "Elabora nanopartículas de oro contenidas en hidrogeles tridimensionales cuyas dimensiones geométricas varían con temperatura y pH, modulando así las propiedades ópticas y electrónicas de las nanopartículas.",
     "LA ELABORACION DE NANOPARTICULAS DE ORO QUE ESTARAN CONTENIDAS DENTRO DE ESTRUCTURAS TRIDIMENSIONALES (HIDROGELES) LAS CUALES PODRAN VARIAR SUS DIMENSIONES GEOMETRICAS EN FUNCION DE LA TEMEPRATURA Y EL pH", 0.88),
],
"131": [
    ("Pirólisis flash de residuos domésticos para producción de energía limpia",
     "Desarrolla un proceso de pirólisis flash que transforma residuos domésticos del campus PUCP (cáscaras, borra de café, huesos) en un líquido combustible limpio, mediante diseño y ensayo de un reactor.",
     "desarrollar un proceso de pirólisis flash que transforme la biomasa en un recurso útil para la producción de energía en una universidad", 0.88),
],
"481": [
    ("Modelos de regresión Beta rectangular y cuantílica para variables limitadas",
     "Propone modelos de regresión más flexibles y robustos para variables continuas acotadas al intervalo [0,1], incluyendo datos fraccionales, regresión cuantílica y extensiones de la Beta rectangular, con enfoque clásico y bayesiano.",
     "extensiones del modelo de regresión Beta Rectangular... modelos de regresión para la mediana o regresión cuantílica cuando la variable dependiente sea limitada", 0.88),
],
"552": [
    ("Cuantificación de ácido carmínico en cochinilla peruana por RMN",
     "Desarrolla un método no separativo basado en RMN y masas por inyección directa para cuantificar ácido carmínico e identificar antraquinonas en la cochinilla peruana, correlacionando con atributos cromáticos.",
     "emplear metodología no separativa, basada en resonancia magnética nuclear (RMN) y masas... tanto para cuantificar el contenido ac. carmínico (1H-RMN)", 0.9),
],
"84": [
    ("Edición de las últimas obras del sociólogo Denis Sulmont",
     "Culmina la edición de las últimas obras académicas del profesor Denis Sulmont, referente de la sociología peruana.",
     "Denis Sulmont; Producción académica; Sociología peruana; Edición de obras", 0.55),
],
"169": [
    ("Redes sociales de escuela, barrio y Facebook en las expectativas educativas de jóvenes limeños",
     "Estudia cómo la interconexión de redes sociales forjadas en la escuela, el barrio y Facebook condiciona la construcción de expectativas educativas y laborales de estudiantes limeños de secundaria de distintos sectores sociales.",
     "este proyecto estudia cómo distintas redes sociales de amistad, forjadas en la escuela, el barrio y Facebook... afectan la construcción de expectativas educativas y laborales", 0.92),
],
"682": [
    ("Cambios en la identidad institucional de las ONG fundacionales peruanas (1990-2016)",
     "Analiza los cambios organizacionales, discursivos y de financiamiento de las ONG peruanas fundadas entre 1960-1980 desde 1990, argumentando que su sentido fundacional de trabajo con poblaciones vulnerables se mantiene pese al viraje hacia el mercado y la gestión eficiente.",
     "Se observará que en el ámbito del desarrollo internacional y local se modifican las reglas del juego para las ONG... el sentido y significado de la acción social fundacional de las ONG se mantienen vigentes", 0.92),
],
"119": [
    ("Bicentenarios latinoamericanos y proyecto de nación en el Perú",
     "Analiza comparativamente (con México, Colombia, Argentina y Bolivia) cómo los proyectos políticos actuales influyen en la evaluación del significado de la independencia, buscando sentar bases para un proyecto de nación democrático, pluralista e inclusivo para el Perú.",
     "analizará de qué manera los proyectos políticos actualmente en curso en los países latinoamericanos influyen sobre la manera en que se evalúa el significado de la independencia... apostar por construir un proyecto de nación democrático, pluralista, multicultural, inclusivo", 0.9),
],
"526": [
    ("Lógicas de mercado y calidad educativa en universidades privadas de la Lima emergente",
     "Analiza la transformación institucional y movilidad social generada por universidades-empresa en sectores emergentes de Lima, examinando comunidades académicas y calidad educativa bajo lógicas de mercado.",
     "TRANSFORMACION INSTITUCIONAL Y MOVILIDAD SOCIAL EN LA UNIVERSIDAD PERUANA. EL CASO DE LAS UNIVERSIDADES EMPRESAS EN SECTORES EMERGENTES", 0.75),
],
"107": [
    ("Autonomía institucional vs. captura del Estado peruano por intereses privados",
     "Analiza el grado de autonomía institucional del Estado peruano frente a la captura por intereses privados, usando como casos el puerto de Paita y el gas de Camisea, en el marco de las reformas neoliberales.",
     "caracterizar el funcionamiento y la naturaleza del Estado peruano en la actualidad... su grado de autonomía institucional o dependencia de los intereses de los intereses privados", 0.9),
],
"172": [
    ("Encuesta Mundial de Valores aplicada al Perú",
     "Aplica la Encuesta Mundial de Valores en el Perú para el estudio de valores sociales, opinión pública y cultura política.",
     "Valores sociales; Opinión pública; Cultura política; Perú", 0.6),
],
"896": [
    ("Bioplásticos a partir de polisacáridos sulfatados de algas verdes para almacenamiento de energía",
     "Extrae polisacáridos sulfatados del alga verde Ulva sp. de la bahía de Paracas para sintetizar un bioplástico biodegradable, flexible y compostable, aplicable en dispositivos de almacenamiento de energía.",
     "se propone extraer los polisacáridos presentes en el alga verde Ulva sp. con el objetivo de sintetizar un nuevo bioplástico... para el desarrollo de nuevos almacenadores de energía flexibles, biodegradables y compostables", 0.92),
],
"470": [
    ("Software de huella de carbono y retorno energético para la pesca peruana",
     "Adapta 'pescaenverde' (ecoetiqueta española de ciclo de vida) al sector pesquero peruano, desarrollando la primera metodología nacional para calcular huella de carbono y tasa de retorno energético de especies capturadas.",
     "el objetivo de este proyecto es entender qué aspectos técnicos del software son necesarios cambiar para una correcta aplicación para el sector pesquero peruano", 0.9),
],
"830": [
    ("Sistema de gestión y trazabilidad de la quinua orgánica con drones y app móvil",
     "Desarrolla un sistema con drones, sensado remoto y una app móvil para el monitoreo y trazabilidad de la producción de quinua orgánica de agricultura familiar en Puno, orientado a la certificación orgánica y exportación.",
     "se usarán tecnologías de drones, sensado remoto, e informática para disponer de informacón ágil y precisa en forma de mapas georeferenciados... para la certificación orgánica de la quinua y el reporte de trazabilidad", 0.9),
],
"284": [
    ("Metodología automatizada para desplegar redes de sensores climáticos en la Amazonía",
     "Formula y valida una metodología de alto grado de automatización (herramientas CAE) para el diseño, despliegue y gestión de redes inalámbricas de sensores de variables climáticas en zonas rurales de la Amazonía peruana.",
     "propone la formulación y validación experimental de una metodología que sistematice y automatice en un alto grado toda la secuencia de operaciones... para el diseño, despliegue y gestión de redes inalámbricas de sensores para variables climáticas", 0.88),
],
"712": [
    ("Generación de proyectos de investigación científica en ingeniería",
     "Apoya la formulación de nuevos proyectos de investigación científica en ingeniería.",
     "Investigación en ingeniería; Formulación de proyectos; Innovación tecnológica; Gestión científica", 0.55),
],
"812": [
    ("Prótesis de miembro superior personalizadas por fabricación digital de bajo costo",
     "Desarrolla una metodología de escaneo 3D, diseño paramétrico y fabricación por impresión 3D para prótesis de mano personalizadas de bajo costo, con evaluación física y psicológica de usuarios y un plan de negocios social.",
     "Desarrollar prótesis personalizadas de bajo costo con tecnología de fabricación digital para atender la necesidad y mejora de acceso a prótesis de miembro superior", 0.9),
],
"333": [
    ("Telemedicina para la salud materno-infantil en la cuenca del río Napo",
     "Instala una red inalámbrica de telefonía e internet que interconecta 15 establecimientos de salud de la cuenca del Napo con el Hospital Regional de Iquitos, para mejorar la atención materno-infantil ante altas tasas de morbimortalidad.",
     "el GTR-PUCP y su socio la Fundación EHAS han instalado una red inalámbrica de comunicaciones de voz (telefonía) y datos... que interconecta a estos 15 establecimientos de salud entre sí y con el Hospital Regional de Iquitos", 0.9),
],
"357": [
    ("Partículas carbonosas esferoidales como indicador de contaminación atmosférica industrial en Lima",
     "Da seguimiento a la contaminación atmosférica por combustión industrial de combustibles fósiles en Lima Metropolitana mediante el registro de perfiles de concentración de partículas carbonosas esferoidales, un indicador químicamente inerte no rastreado por los programas oficiales.",
     "un indicador de la contaminación ambiental por esta actividad es la partícula carbonosa esferoidal... el presente estudio propone el seguimiento de la contaminación atmosférica ocasionada por los procesos de combustión industrial", 0.88),
],
"433": [
    ("Diagnóstico termográfico preventivo del pie diabético",
     "Desarrolla un procedimiento clínico no invasivo basado en patrones plantares termográficos para el monitoreo y diagnóstico preventivo del pie diabético, con protocolo de adquisición, software de procesamiento y guía clínica.",
     "Un nuevo procedimiento clínico para el monitoreo y diagnóstico preventivo sistemático (rápido) y no-invasivo de pie diabético... basa en el análisis de los patrones plantares termográficos", 0.92),
],
"366": [
    ("Aprovechamiento integral de hojas de caña de azúcar en energía y material puzolánico",
     "Desarrolla un proceso integrado que biobriquetea hojas de caña de azúcar para generar calor por combustión y produce, a partir de las cenizas resultantes, un material puzolánico apto como aditivo del cemento (20% de sustitución).",
     "Se desarrolló un proceso de aprovechamiento integral para las HCA... las cenizas resultantes de este proceso fueron caracterizadas según normas ASTM calificando como una puzolana", 0.9),
],
"905": [
    ("Nanogenerador triboeléctrico biodegradable a partir de almidón de papa andina",
     "Fabrica un nanogenerador triboeléctrico biodegradable (bio-TENG) con láminas flexibles de biopolímeros de almidón de papa andina, como alternativa sostenible a los TENGs de polímeros sintéticos para energía de dispositivos portátiles.",
     "se propone fabricar un nanogenerador triboeléctrico biodegradable (bio-TENG), utilizando láminas flexibles de biopolímeros y bionanocompuestos como superficies activas... Se usará almidón como principal insumo", 0.92),
],
"604": [
    ("Sustitución parcial de diésel por gas natural en motores de combustión a nivel del mar",
     "Evalúa experimentalmente los efectos del uso simultáneo de diésel y gas natural sobre desempeño y emisiones de motores de encendido por compresión a nivel del mar, sentando bases para un sistema electrónico de conversión Diesel/gas.",
     "evaluar los efectos del uso simultáneo de los combustibles diesel y gas natural sobre los parámetros de desempeño y emisiones de motores de encendido por compresión", 0.88),
],
"223": [
    ("Nanopartículas de cobre antibacterianas impregnadas en tela médica",
     "Sintetiza nanopartículas de cobre por vía química y las impregna en tela para evaluar sus propiedades bactericidas frente a bacterias patógenas, con potencial para prevenir infecciones hospitalarias.",
     "las nanopartículas de cobre han llamado fuertemente la atención de los investigadores por presentar propiedades antibactericidas... impregnarlas en tela con la finalidad de determinar sus propiedades bacetricidas", 0.9),
],
"79": [
    ("Recubrimientos nanoestructurados en aluminio por fricción-agitación (FSP)",
     "Implementa procesos de soldadura y procesamiento por fricción-agitación (FSW/FSP) para fabricar recubrimientos superficiales nanoestructurados reforzados con nanopartículas sobre aleación de aluminio AA5083-H116, evaluando microestructura, propiedades mecánicas y resistencia al desgaste.",
     "Se fabricaron compuestos superficiales nanoestructurados (recubrimientos) empleando como material base la aleación de aluminio AA5083-H116 y como refuerzo nanopartículas. El proceso empleado para este trabajo fue el de FSP", 0.88),
],
"49": [
    ("Sistema de trazabilidad de ganado vacuno con RFID y gestión web",
     "Diseña e implementa un sistema de trazabilidad de ganado vacuno mediante microchips RFID subcutáneos y un sistema de información web que gestiona raza, propietario y vacunación del animal.",
     "el análisis, el diseño y la implementación de un sistema de trazabilidad de ganado vacuno... basará en un sistema de identificación por radio frecuencia (RFID)", 0.88),
],
"313": [
    ("Herramientas de diseño de agitadores para minería y agroindustria",
     "Desarrolla y sistematiza herramientas de diseño de agitadores industriales mediante metodologías experimentales, simulación numérica y escalamiento, para los sectores minero y agroalimentario.",
     "Herramienta para el diseño de agitadores para el sector minero y agroalimentario", 0.75),
],
"561": [
    ("Vibroelastografía por ondas de rastreo para diagnóstico de cáncer de mama",
     "Valida estimadores de velocidad de onda de corte (crawling wave sonoelastography) con configuraciones de excitación paralela y normal en fantomas de gelatina, para diagnóstico de cáncer de mama en la población peruana.",
     "a new low-cost estimator based on spatial wavelength averaging... Results showed favorable estimation mean accuracy (93.8%) on the homogeneous phantoms", 0.88),
],
"882": [
    ("Prótesis mioeléctrica transradial de bajo costo con filamento PET reciclado",
     "Diseña una prótesis mioeléctrica transradial personalizable con retroalimentación háptica, fabricada con filamento ABS/PET reciclado mediante impresión 3D, para hacer accesible la rehabilitación a personas de bajos recursos en el Perú.",
     "el diseño, desarrollo e implementación de una prótesis mioeléctrica transradial personalizable con sistema de retroalimentación háptico de bajo costo; para así, permitir el acceso a tecnología de rehabilitación a personas de bajos recursos", 0.9),
],
"630": [
    ("Interfaz cerebro-máquina adaptativa para personas con discapacidad motriz severa",
     "Desarrolla un sistema de asistencia inteligente controlado por interfaz cerebro-máquina no invasiva (EEG/EMG) que aprende gradualmente las preferencias del usuario para controlar dispositivos, una silla de ruedas motorizada y un teclado virtual.",
     "el desarrollo una sistema de asistencia inteligente controlado por una Interfaz Cerebro-Maquina (BMI)... controlar dispositivos electrónicos... controlar una silla de rueda motorizada... comunicación a través de un teclado virtual", 0.9),
],
"633": [
    ("Mucílago atomizado de Sanky como aditivo alimentario funcional",
     "Optimiza la extracción alcalina y deshidratación por atomización de mucílago de residuos de Sanky (cactus), obteniendo un aditivo en polvo con propiedades reológicas similares a la goma arábiga.",
     "desarrollar un proceso óptimo para la obtención de mucilago atomizado de Sanky, permitiendo aprovechar las mermas o residuos... un aditivo funcional en polvo con propiedades reológicas similares a la goma arábiga", 0.9),
],
"592": [
    ("Incubadora neonatal con respirador artificial integrado",
     "Desarrolla una incubadora neonatal con sistema de respiración asistida integrado.",
     "Incubadoras neonatales; Respiración asistida; Dispositivos médicos; Ingeniería neonatal", 0.65),
],
"923": [
    ("Comunica Investiga Lab: comunidad estudiantil de investigación en comunicaciones",
     "Crea una comunidad estudiantil interdisciplinaria de Comunicaciones PUCP para la construcción colectiva de investigaciones y soluciones innovadoras con impacto social, ganadora del CAP Innovación PUCP 2021.",
     "Somos una comunidad que busca conectar estudiantes de todas las especialidades y niveles de formación de Comunicaciones PUCP para la construcción colectiva de conocimientos y soluciones innovadoras", 0.8),
],
"109": [
    ("Drama histórico sobre Bolognesi en la Guerra del Pacífico",
     "Crea una obra de teatro histórico sobre Francisco Bolognesi en la batalla de Arica, dentro de la dramaturgia peruana.",
     "Teatro histórico; Francisco Bolognesi; Guerra del Pacífico; Dramaturgia peruana", 0.65),
],
"491": [
    ("Ficción televisiva peruana y memoria social (2014-2015)",
     "Analiza la relación entre la ficción televisiva peruana y la constitución de la memoria social del país, identificando contextos sociales, históricos y políticos de las narrativas de 2014-2015, en diálogo con la red OBITEL.",
     "establecer cuáles son las relaciones entre la ficción televisiva peruana y la memoria social de nuestro país, además de identificar los contextos sociales, históricos y políticos", 0.9),
],
"596": [
    ("Estereotipos, prejuicio intergrupal e identidades regionales entre Lima y Huamanga",
     "Investiga en tres fases cualitativas y cuantitativas cómo las percepciones estereotípicas mutuas, las emociones intergrupales y la ideología política configuran las identidades colectivas limeña, huamanguina y nacional en un contexto de conflicto intergrupal.",
     "se plantea una investigación en tres fases. Primero una aproximación cualitativa para identificar percepciones estereotípicas mutuas de los pobladores de Lima y Huamanga... establecer el impacto de las emociones intergrupales y la ideología política en la configuración de las identidades colectivas", 0.9),
],
"252": [
    ("Neurociencia aplicada al aprendizaje y la cognición",
     "Explora aportes de la neurociencia a la comprensión del aprendizaje, la educación y la cognición.",
     "Neurociencia; Aprendizaje; Educación; Cognición", 0.55),
],
"910": [
    ("Impacto psicosocial e identitario del legado de los Juegos Panamericanos Lima 2019",
     "Analiza, mediante estudios cualitativos, cuantitativos y experimentales, el impacto psicosocial de las actividades del Proyecto Especial Legado Lima 2019 como rituales sociales que promueven cohesión, identidad ciudadana y bienestar.",
     "se consideran las actividades relacionadas a los juegos y al PEL como rituales sociales que promoverían la cohesión y el bienestar en la sociedad... indicadores identitarios, de ciudadanía y promoción del bienestar", 0.92),
],
"321": [
    ("Sentido de comunidad y bienestar en asentamientos humanos limeños",
     "Explora las relaciones entre sentido de comunidad, participación y dimensiones colectivas e individuales del bienestar en pobladores de asentamientos humanos en contextos de pobreza en Lima.",
     "explora las relaciones entre el sentido de comunidad y el bienestar en un grupo de pobladores de asentamientos humanos en Lima... la participación en sus comunidades como una estrategia que fortalece la identificación", 0.9),
],
"749": [
    ("Datos normativos del Rorschach en niños asháninkas y cusqueños",
     "Construye datos normativos culturales del Sistema Comprehensivo del Rorschach comparando respuestas populares y relaciones interpersonales en niños asháninkas, andinos cusqueños y limeños.",
     "DIVERSIDAD CULTURAL EN LAS RESPUESTAS POPULARES AL RORSCHACH EN UNA MUESTRA DE NIÑOS ASHANINKAS Y NIÑOS DEL CUSCO RURAL... RELACIONES INTERPERSONALES EN MENORES DE DIEZ Y ONCE AÑOS ASHANINKAS, ANDINOS Y LIMEÑOS", 0.85),
],
"483": [
    ("Apoyo a la autonomía docente y compromiso estudiantil en universitarios peruanos",
     "Muestra, con diseño longitudinal en 336 estudiantes universitarios peruanos, que el compromiso agéntico de los estudiantes predice a su vez incrementos en la enseñanza que apoya la autonomía percibida por parte de los profesores.",
     "students' early-semester agentic engagement predicted longitudinal increases in perceived autonomy-supportive teaching, which suggests that students' classroom engagement may recruit greater perceived autonomy support", 0.85),
],
"719": [
    ("Neurocognición de la percepción de emociones en la interacción humano-robot",
     "Desarrolla tecnología EEG y reconocimiento de emociones faciales para estudiar experimentalmente la percepción y acción de movimientos, y la activación de neuronas espejo ante emociones elicitadas por humanos y robots humanoides.",
     "el desarrollo de tecnología EEG y un sistema de reconocimiento de emociones faciales para la implementación de dos paradigmas experimentales neurocognitivos... percepción de emociones elicitadas por medio de movimientos de humanos y robots humanoides", 0.9),
],
"402": [
    ("Desarrollo cognitivo y juicio moral en adolescentes shipibo y quechua",
     "Explora, desde el marco piagetiano, las operaciones lógicas y el desarrollo del juicio moral en adolescentes de comunidades shipibo (Ucayali) y quechua (Ayacucho), y su relación con percepciones sobre la educación.",
     "nos interesa explorar específicamente las operaciones lógicas y el desarrollo del juicio moral de estos adolescentes... explorar la manera en que se expresan en las culturas específicas a las que pertenecen los adolescentes", 0.85),
],
"861": [
    ("Creación de capacidades en antropología visual y cultural postconflicto",
     "Crea capacidades de investigación colaborativa en antropología cultural y visual en contextos posconflicto latinoamericanos.",
     "la creación de capacidades para la investigación colaborativa entre ambas universidades, con énfasis en el valor de la antropología cultural y visual en contextos post conflicto", 0.8),
],
"48": [
    ("Transversalización de género en el proyecto PROPOMAC en Lambayeque",
     "Promueve la incorporación transversal de la perspectiva de equidad de género en el proyecto PROPOMAC para mejorar las condiciones de vida de caseríos de Lambayeque.",
     "lograr la incorporación transversal de la perspectiva de género en el proyecto, al promover y crear las condiciones para una efectiva participación de la mujer", 0.78),
],
"291": [
    ("Evaluación de impacto socioambiental de industrias extractivas",
     "Evalúa el impacto y la gobernanza asociados a las industrias extractivas.",
     "Industrias extractivas; Impacto socioambiental; Evaluación de impacto; Gobernanza", 0.6),
],
"530": [
    ("Régimen jurídico de la doble imposición tributaria internacional",
     "Analiza el régimen jurídico de la doble imposición tributaria internacional y sus convenios.",
     "Doble Imposición; Tributación Internacional; Derecho Tributario; Convenios Fiscales", 0.65),
],
"226": [
    ("Segmentación del mercado laboral peruano: diferenciales de ingresos y movilidad",
     "Analiza la segmentación de los mercados laborales en el Perú, sus diferenciales de ingresos y la movilidad laboral entre segmentos.",
     "Mercado laboral; Segmentación; Diferenciales salariales; Movilidad laboral", 0.62),
],
"778": [
    ("Determinantes de la inversión privada en una economía minero-exportadora",
     "Modela los determinantes de la inversión privada en una economía primario-exportadora peruana con libre movilidad de capitales.",
     "PRIVATE INVESTMENT IN A MINING EXPORT ECONOMY: A MODEL FOR PERU", 0.78),
],
"610": [
    ("El Perú frente al Acuerdo Transpacífico (TPP) y la integración Asia-Pacífico",
     "Analiza los desafíos del Perú frente al Acuerdo Transpacífico y el rol del potencial de mercado en explicar las distintas trayectorias de integración regional entre América Latina y Asia-Pacífico.",
     "nuestro objetivo es identificar el papel del potencial de mercado a la hora de explicar las trayectorias distintas de integracin regional en Amrica Latina y en Asia-Pacfico", 0.8),
],
"730": [
    ("Lenguaje judicial claro y acceso a la justicia en procesos de familia",
     "Explora el estado del lenguaje judicial escrito en procesos de familia con poblaciones vulnerables en Lima Sur, encontrando severas dificultades de los jueces para escribir con claridad y de las usuarias para comprender el lenguaje técnico.",
     "The results show a part that judges interviewed have severe difficulties to write clearly judgments that are directed to the citizens of vulnerable populations... women do not understand the technical language of judgments", 0.92),
],
"144": [
    ("Desafíos del constitucionalismo peruano del siglo XXI",
     "Reflexiona sobre los desafíos del constitucionalismo y el derecho público en el Perú del siglo XXI.",
     "Constitucionalismo; Derecho público; Democracia; Perú", 0.58),
],
"280": [
    ("Metodología racional para el análisis y valoración de la prueba pericial",
     "Propone una metodología, criterios y herramientas para que las autoridades judiciales analicen y valoren racionalmente la prueba pericial, permitiendo el control intersubjetivo del razonamiento y evitando la arbitrariedad.",
     "no existe a nivel normativo, jurisprudencial o doctrinario una metodología, criterios y herramientas que permitan analizar y valorar racionalmente si la prueba pericial ofrecida en un proceso proporciona información confiable", 0.9),
],
"640": [
    ("Ciencia y poder político en el Perú virreinal",
     "Continúa el estudio de la relación entre ciencia, poder político e historia intelectual en el Virreinato del Perú.",
     "Ciencia colonial; Poder político; Virreinato del Perú; Historia intelectual", 0.65),
],
"230": [
    ("Ciudadanía intercultural y acción afirmativa en la educación superior",
     "La red RIDEI-PUCP promueve el ejercicio de la ciudadanía intercultural en contextos de diversidad, con talleres regionales y acompañamiento a programas de acción afirmativa en universidades de Cusco y Ayacucho.",
     "un equipo interdisciplinario que realiza investigaciones sobre el ejercicio de la ciudadanía en contextos de diversidad cultural y promueve acciones de educación intercultural... incorporación del enfoque de ciudadanía intercultural en programas de acción afirmativa", 0.88),
],
"740": [
    ("Diccionario anotado de la Lengua de Señas Peruana",
     "Elabora un diccionario anotado de la LSP con al menos 500 entradas léxicas, cada una con video, glosa, descripción morfosintáctica y fonológica, y transcripción a SignWriting, sentando las bases metodológicas para diccionarios de LSP.",
     "elaborar un diccionario anotado de la Lengua de Señas Peruana... sentar las bases para la creación de diccionarios en LSP", 0.92),
],
"276": [
    ("Historiografía y teoría de la historia en América Latina",
     "Reflexiona sobre la historiografía latinoamericana y la teoría de la historia en la producción académica regional.",
     "Historiografía; América Latina; Teoría de la historia; Producción académica", 0.58),
],
"699": [
    ("Autoridad, negociación y crisis política en el gobierno del virrey Conde de Castellar",
     "Estudia la crisis política del gobierno del virrey Conde de Castellar (1674-1678), examinando redes de beneméritos y allegados, y circuitos alternativos de plata en el comercio intercolonial del Pacífico.",
     "BENEMERITOS, CRIADOS Y ALLEGADOS DURANTE EL GOBIERNO DEL VIRREY CONDE DE CASTELLAR... THE ALTERNATIVE CIRCUITS OF SILVER: LIMA AND THE INTER-COLONIAL TRADE IN THE PACIFIC", 0.88),
],
"283": [
    ("Fundamentos filosóficos del interculturalismo y multiculturalismo educativo latinoamericano",
     "Compara los fundamentos filosóficos y las políticas del multiculturalismo anglosajón y el interculturalismo latinoamericano, evaluando sus aplicaciones recientes en México, Perú, Bolivia y Ecuador.",
     "hacer un análisis comparado entre las políticas de la diferencia del multiculturalismo anglosajón y el interculturalismo latinoamericano así como de los fundamentos filosóficos que les son propios", 0.9),
],
"761": [
    ("Modelamiento de distribución de especies de alta montaña ante el cambio climático",
     "Compara mediante MaxEnt el impacto del cambio climático (RCP 2.6 y 8.5, horizonte 2050) en la distribución de especies focales de alta montaña en los Andes tropicales, los Alpes de Nueva Zelanda y la vegetación alpina australiana.",
     "llevar a cabo un análisis comparativo de estos impactos utilizando técnicas estadísticas de modelamiento de distribución de especies en tres ecosistemas de alta montaña... Se cuantificará la tasa de cambio en la extensión del rango de distribución", 0.92),
],
"577": [
    ("Equilibrio político y destitución del virrey Conde de Castellar (Etapa VI)",
     "Sexta etapa del estudio de los mecanismos de equilibrio político colonial: analiza el gobierno y la inédita destitución del virrey Conde de Castellar en 1678 mediante su juicio de residencia y correspondencia, iluminando la estabilidad política del Perú virreinal.",
     "estudiar los mecanismos de equilibrio político en el Perú colonial durante los Austrias, a través del estudio del gobierno del virrey Conde de Castellar, quien fuera depuesto por el rey en 1678", 0.9),
],
"651": [
    ("Política de las emociones entre los intelectuales del Perú posbélico",
     "Estudia la política de las emociones entre los intelectuales del Perú posbélico (tras la Guerra del Pacífico) desde la historia cultural.",
     "Política de las emociones; Intelectuales; Perú posbélico; Historia cultural... NI AMAR NI ODIAR CON FIRMEZA. CULTURA Y EMOCIONES EN EL PERU POSBELICO", 0.78),
],
"240": [
    ("Excavación arqueológica del Proyecto San José de Moro (2012)",
     "Excavación arqueológica de campo del sitio moche de San José de Moro en el valle de Jequetepeque.",
     "Arqueología moche; San José de Moro; Excavación arqueológica; Valle de Jequetepeque", 0.62),
],
"783": [
    ("Construcción ideológica y partidaria del APRA (1928-1930)",
     "Analiza la construcción ideológica y partidaria del APRA en torno a la renuncia de Haya de la Torre y la sublevación aprista de 1929.",
     "Víctor Raúl Haya de la Torre; APRA; Historia política; 1928-1930... LA REVOLUCION: PLAN Y PORMENORES SOBRE LA SUBLEVACION APRISTA DE 1929", 0.78),
],
"320": [
    ("Curso de latín orientado a peruanistas",
     "Elabora un curso de latín, desde la época clásica hasta el latín colonial peruano, dirigido a estudiantes e investigadores de temas peruanos, dado su uso en la producción científica colonial.",
     "elaboración de un curso de latín dirigido a estudiantes e investigadores de temas peruanos... Se pone especial énfasis en el latín colonial peruano, ya que esta lengua fue utilizada en la producción científica peruana", 0.85),
],
"588": [
    ("Alfabeto oficial e identidad cultural de la lengua bora",
     "Explora cómo se discute e implementa el alfabeto oficial de la lengua bora en las cuencas de los ríos Momón, Ampiyacu y Yaguasyacu, y profundiza en la caracterización fonológica del tono y el contacto con el español.",
     "cómo se discute e implementa el alfabeto oficial, que se desarrolla en el Ministerio de Educación, en las cuencas de los ríos Momón, Ampiyacu y Yaguasyacu... profundizará en cómo se comporta el tono en esta lengua", 0.9),
],
"392": [
    ("Mejora de la formación docente en servicio en la educación superior peruana",
     "Busca mejorar la formación docente en servicio en instituciones de educación superior del Perú.",
     "Formación docente en servicio; Educación superior; Desarrollo profesional; Perú", 0.65),
],
"72": [
    ("Efecto de un programa de estrategias innovadoras docentes en comunicación y matemática",
     "Evalúa cuasi-experimentalmente, con modelo de Rasch, el efecto de un programa de intervención docente con estrategias innovadoras en comunicación y matemática sobre el rendimiento de estudiantes públicos de la zona sur del país, explorando también el rol del involucramiento parental.",
     "verificar el efecto de un programa de intervención educativa que propone estrategias innovadoras... verificar la mejora de estas competencias en los estudiantes de educación primaria y secundaria", 0.9),
],
"785": [
    ("Evaluación ex-post de la Ley del Artesano (Ley 29073)",
     "Evalúa ex-post los impactos, alcances y limitaciones de la Ley del Artesano peruana mediante análisis comparativo con legislación regional, para recomendar mejoras en la política sectorial artesanal.",
     "el proyecto plantea una evaluación ex-post de dicha Ley a través de la evaluación de sus impactos, la verificación de los procesos de implementación de su reglamento... para aportar desde el ámbito académico a una mejora en decisiones futuras", 0.9),
],
"803": [
    ("Espíritu del bosque: investigación-creación artística en la Amazonía de Pucallpa",
     "Investiga y crea propuestas artísticas (dibujo, fotografía, óleo) a partir del trabajo de campo en el bosque amazónico cercano a Pucallpa, interpretando el 'espíritu del bosque' como identidad del hombre amazónico.",
     "se desarrollará una investigación de las formas y el espacio propios del Bosque Amazónico cercanos a la ciudad de Pucallpa... se investigará el 'bosque' como tema base que refleja la identidad del espíritu del hombre amazónico", 0.85),
],
"642": [
    ("Implementación comparada de recomendaciones de comisiones de la verdad latinoamericanas",
     "Construye una base de datos cualitativa y una tipología de recomendaciones de 20 comisiones de la verdad de distintos países, examinando empíricamente los factores que influyen en su implementación.",
     "construir una base de datos cualitativa acerca de la implementación de recomendaciones de diversas Comisiones de la Verdad... Son 20 países involucrados en dicho estudio", 0.9),
],
"311": [
    ("Red ALFA-DHES de derechos humanos en la educación superior latinoamericana",
     "Mejora la calidad, pertinencia y accesibilidad de la educación superior en derechos humanos en América Latina a través de la red académica ALFA-DHES.",
     "la red ALFA-DHES tiene como objetivo central la mejora de la calidad, pertinencia y accesibilidad de la Educación Superior en América Latina en materia de Derechos Humanos", 0.8),
],
"488": [
    ("Remoción de mercurio de residuos de laboratorio con carbón activado de aguaje modificado",
     "Modifica carbón activado de semillas de aguaje con óxido de manganeso para mejorar la adsorción de mercurio en desechos acuosos de laboratorio, ajustándose al modelo de Freundlich, cumpliendo la norma ISO 17025.",
     "se empleará carbón activado obtenido a partir de semillas de aguaje... modificado con nitrato de manganeso mediante una impregnación húmeda a fin de aumentar su capacidad de adsorción de mercurio", 0.9),
],
"587": [
    ("Multirresidencia y migración circular como adaptación familiar al deterioro ambiental",
     "Estudia en 400 familias rurales de Piura y Puno cómo la multirresidencia, la migración circular y el trabajo infantil/juvenil constituyen estrategias de adaptación familiar frente a los deterioros medioambientales, más allá de las nociones de 'refugiados climáticos'.",
     "el proyecto propone estudiar en qué medida la multi residencia, la migración circular y la evolución del trabajo de los niños y jóvenes constituyen estrategias de adaptación de las familias e implican un proceso de depresión rural", 0.9),
],
"449": [
    ("Ciudades inteligentes: tecnologías y gestión urbana",
     "Explora tecnologías urbanas e innovación en gestión para el desarrollo de ciudades inteligentes.",
     "Ciudades inteligentes; Tecnologías urbanas; Gestión urbana; Innovación", 0.55),
],
"649": [
    ("Escuela internacional de posgrado sobre sociedad, ambiente y cambio climático",
     "Organiza la primera escuela internacional de posgrado sobre sociedad, ambiente y cambio climático como espacio de formación y cooperación académica.",
     "Cambio climático; Sociedad y ambiente; Formación de posgrado; Cooperación académica", 0.65),
],
"930": [
    ("PosTacto: investigación-creación en danza sobre el contacto post-pandemia",
     "Investiga desde la danza y la práctica artística cómo el concepto de 'contacto' se resignifica tras la pandemia de COVID-19, explorando el cuerpo, la percepción y el contagio de ideas en un proceso de creación colectiva.",
     "repensar el concepto de CONTACTO luego de haber atravesado como sociedad el estado de emergencia mundial causada por el COVID19... el contacto como vínculo y ahora también como posibilidad de contagio de ideas y posturas creativas", 0.9),
],
}

REUSE_BATCH06 = [
    ("Gobernanza urbana y desigualdad territorial en Lima", [
        ("1", "Zonificación de tejidos urbanos homogéneos en la periferia de Lima-Callao"),
        ("449", "Ciudades inteligentes: tecnologías y gestión urbana"),
    ]),
    ("Gobernanza local del agua y derecho consuetudinario", [
        ("393", "Interacción transectorial para la seguridad hídrica y resiliencia climática en Santa Eulalia"),
    ]),
    ("Cambio climático, recursos naturales y desarrollo sostenible", [
        ("2", "Vulnerabilidad de cultivos y agrobiodiversidad frente al cambio climático en Piura"),
        ("761", "Modelamiento de distribución de especies de alta montaña ante el cambio climático"),
        ("649", "Escuela internacional de posgrado sobre sociedad, ambiente y cambio climático"),
    ]),
    ("Óptica cuántica y coherencia en sistemas de qubits", [
        ("467", "Fases geométricas y complementariedad en polarimetría cuántica de un fotón"),
    ]),
    ("Foliaciones holomorfas en variedades complejas", [
        ("760", "Webs holomorfos e hipersuperficies Levi-flat con singularidades"),
        ("423", "Clasificación analítico-topológica de gérmenes de foliaciones en dimensión 2 y 3"),
        ("498", "Singularidades de foliaciones holomorfas de codimensión uno nilpotentes"),
    ]),
    ("Química analítica y control de calidad del café peruano", [
        ("372", "Perfil químico multivariable de café y cacao peruano por RMN y masas"),
    ]),
    ("Películas delgadas semiconductoras de amplio ancho de banda", [
        ("849", "Dopaje con terbio en películas conductoras transparentes ITO y AZO"),
    ]),
    ("Álgebra y construcción explícita de soluciones de ecuaciones", [
        ("9", "Construcción y estudio de soluciones de ecuaciones algebraicas y diferenciales"),
    ]),
    ("Materiales poliméricos funcionales y biomateriales", [
        ("517", "Hidrogeles conmutables con nanopartículas de oro sensibles a temperatura y pH"),
        ("223", "Nanopartículas de cobre antibacterianas impregnadas en tela médica"),
    ]),
    ("Modelización matemática y métodos estadísticos aplicados", [
        ("39", "Modelos de regresión Beta y alternativos para datos proporcionales"),
        ("481", "Modelos de regresión Beta rectangular y cuantílica para variables limitadas"),
    ]),
    ("Bioplásticos y envases biodegradables a partir de recursos nativos", [
        ("896", "Bioplásticos a partir de polisacáridos sulfatados de algas verdes para almacenamiento de energía"),
    ]),
    ("Análisis de ciclo de vida y sostenibilidad energética", [
        ("470", "Software de huella de carbono y retorno energético para la pesca peruana"),
    ]),
    ("Tecnologías digitales, TIC y desarrollo", [
        ("830", "Sistema de gestión y trazabilidad de la quinua orgánica con drones y app móvil"),
    ]),
    ("Redes de sensores inalámbricos para monitoreo ambiental urbano", [
        ("284", "Metodología automatizada para desplegar redes de sensores climáticos en la Amazonía"),
    ]),
    ("Tecnología biomédica y asistiva desarrollada en el Perú", [
        ("812", "Prótesis de miembro superior personalizadas por fabricación digital de bajo costo"),
        ("882", "Prótesis mioeléctrica transradial de bajo costo con filamento PET reciclado"),
        ("630", "Interfaz cerebro-máquina adaptativa para personas con discapacidad motriz severa"),
        ("592", "Incubadora neonatal con respirador artificial integrado"),
    ]),
    ("Ultrasonido cuantitativo para diagnóstico clínico", [
        ("561", "Vibroelastografía por ondas de rastreo para diagnóstico de cáncer de mama"),
    ]),
    ("Optimización de agitadores industriales para procesamiento de minerales", [
        ("313", "Herramientas de diseño de agitadores para minería y agroindustria"),
    ]),
    ("Historia e industria de la televisión peruana", [
        ("491", "Ficción televisiva peruana y memoria social (2014-2015)"),
    ]),
    ("Adaptación de pruebas psicométricas proyectivas en población peruana", [
        ("749", "Datos normativos del Rorschach en niños asháninkas y cusqueños"),
    ]),
    ("Teoría de la autodeterminación en la motivación educativa", [
        ("483", "Apoyo a la autonomía docente y compromiso estudiantil en universitarios peruanos"),
    ]),
    ("Minería, conflicto socioambiental y gestión del agua", [
        ("291", "Evaluación de impacto socioambiental de industrias extractivas"),
    ]),
    ("Tributación internacional y convenios de doble imposición", [
        ("530", "Régimen jurídico de la doble imposición tributaria internacional"),
    ]),
    ("Política monetaria y teoría macroeconómica en el Perú", [
        ("778", "Determinantes de la inversión privada en una economía minero-exportadora"),
    ]),
    ("Historia política y social del Virreinato del Perú", [
        ("640", "Ciencia y poder político en el Perú virreinal"),
        ("699", "Autoridad, negociación y crisis política en el gobierno del virrey Conde de Castellar"),
        ("577", "Equilibrio político y destitución del virrey Conde de Castellar (Etapa VI)"),
    ]),
    ("Tecnologías y recursos lingüísticos para la lengua de señas peruana", [
        ("740", "Diccionario anotado de la Lengua de Señas Peruana"),
    ]),
    ("Documentación y tipología de lenguas amazónicas peruanas", [
        ("588", "Alfabeto oficial e identidad cultural de la lengua bora"),
    ]),
    ("Formación e innovación docente", [
        ("392", "Mejora de la formación docente en servicio en la educación superior peruana"),
        ("72", "Efecto de un programa de estrategias innovadoras docentes en comunicación y matemática"),
    ]),
    ("Memoria, reparaciones y ciudadanía en el posconflicto", [
        ("642", "Implementación comparada de recomendaciones de comisiones de la verdad latinoamericanas"),
    ]),
    ("Investigación y conservación del patrimonio arqueológico y arquitectónico", [
        ("240", "Excavación arqueológica del Proyecto San José de Moro (2012)"),
    ]),
    ("Materiales adsorbentes y tratamiento de contaminantes orgánicos en agua", [
        ("488", "Remoción de mercurio de residuos de laboratorio con carbón activado de aguaje modificado"),
    ]),
]

# New normalized topics introduced in this batch.
# Note: 904/898 are folded directly into a single NEW_NORMALIZED entry
# (rather than via REUSE_BATCH06) because 898 reuses a topic defined for the
# first time in this same batch by 904 — REUSE is applied before
# NEW_NORMALIZED is merged in, so a same-batch REUSE reference would fail.
NEW_NORMALIZED_BATCH06 = {
    "Transformación del paisaje periurbano en ciudades intermedias": (
        "Análisis de la transformación del paisaje periurbano y su gestión sostenible en ciudades intermedias peruanas.",
        [("824", "Transformación del paisaje periurbano en ciudades intermedias: Cajamarca 2007-2017")],
    ),
    "Astronomía observacional de ocultaciones y astrometría": (
        "Observación de ocultaciones astronómicas como técnica de astrometría de cuerpos del sistema solar.",
        [("36", "Ocultaciones astronómicas para astrometría del sistema solar")],
    ),
    "Seguridad alimentaria y biotoxinas marinas": (
        "Cuantificación de biotoxinas marinas en productos hidrobiológicos para garantizar la seguridad alimentaria.",
        [("442", "Cuantificación de biotoxinas lipofílicas marinas en moluscos bivalvos")],
    ),
    "Desempeño de tecnologías fotovoltaicas en el Perú": (
        "Caracterización del desempeño técnico-económico y la degradación de distintas tecnologías fotovoltaicas bajo las condiciones climáticas peruanas.",
        [
            ("904", "Desempeño de módulos fotovoltaicos bifaciales bajo el clima de Lima"),
            ("898", "Rendimiento y degradación de tecnologías fotovoltaicas emergentes con IA y plataforma pública"),
        ],
    ),
    "Arqueometría numismática de aleaciones metálicas peruanas": (
        "Estudio composicional no destructivo de aleaciones metálicas históricas peruanas para reconstruir procesos económicos.",
        [("675", "Arqueometría de la composición química de las monedas de Sol de plata (1863-1935)")],
    ),
    "Espectroscopia LIBS para caracterización de suelos": (
        "Desarrollo de protocolos de espectroscopia de plasma inducido por láser para clasificar y monitorear la calidad de suelos.",
        [("494", "Protocolo LIBS para determinar la calidad y el carbono de suelos")],
    ),
    "Grandes desviaciones en sistemas de partículas interactuantes": (
        "Estudio de principios de grandes desviaciones en modelos estocásticos de partículas interactuantes.",
        [("659", "Principio de grandes desviaciones para un modelo de reacción-difusión estocástico")],
    ),
    "Bioquímica postcosecha de cultivos andinos nutracéuticos": (
        "Estudio de los procesos metabólicos postcosecha que determinan la composición nutracéutica de cultivos andinos.",
        [("775", "Modulación metabólica del secado postcosecha de la maca para enriquecimiento nutracéutico")],
    ),
    "Pirólisis de biomasa residual para producción de energía": (
        "Desarrollo de procesos de pirólisis para transformar residuos orgánicos en recursos energéticos.",
        [("131", "Pirólisis flash de residuos domésticos para producción de energía limpia")],
    ),
    "Química analítica de colorantes naturales peruanos": (
        "Desarrollo de métodos analíticos no separativos para cuantificar y caracterizar colorantes naturales peruanos.",
        [("552", "Cuantificación de ácido carmínico en cochinilla peruana por RMN")],
    ),
    "Edición y preservación de obras académicas peruanas": (
        "Edición y publicación del legado académico de investigadores peruanos.",
        [("84", "Edición de las últimas obras del sociólogo Denis Sulmont")],
    ),
    "Redes sociales juveniles y expectativas educativo-laborales": (
        "Estudio de cómo las redes sociales de distintos ámbitos condicionan las expectativas educativas y laborales de los jóvenes.",
        [("169", "Redes sociales de escuela, barrio y Facebook en las expectativas educativas de jóvenes limeños")],
    ),
    "Identidad institucional y transformación de las ONG peruanas": (
        "Análisis de los cambios organizacionales y discursivos en la identidad y el rol de las ONG peruanas.",
        [("682", "Cambios en la identidad institucional de las ONG fundacionales peruanas (1990-2016)")],
    ),
    "Bicentenarios y proyecto de nación en América Latina": (
        "Análisis comparado de cómo las conmemoraciones del bicentenario influyen en la construcción de proyectos de nación latinoamericanos.",
        [("119", "Bicentenarios latinoamericanos y proyecto de nación en el Perú")],
    ),
    "Mercantilización de la educación superior privada en el Perú": (
        "Análisis de las lógicas de mercado y su impacto en la calidad educativa de universidades privadas peruanas.",
        [("526", "Lógicas de mercado y calidad educativa en universidades privadas de la Lima emergente")],
    ),
    "Autonomía institucional y captura del Estado peruano": (
        "Análisis del grado de autonomía institucional del Estado peruano frente a la captura por intereses privados.",
        [("107", "Autonomía institucional vs. captura del Estado peruano por intereses privados")],
    ),
    "Encuestas de valores y cultura política en el Perú": (
        "Aplicación de encuestas internacionales de valores para el estudio de la cultura política peruana.",
        [("172", "Encuesta Mundial de Valores aplicada al Perú")],
    ),
    "Fortalecimiento de capacidades para la formulación de proyectos de investigación": (
        "Apoyo institucional a la formulación de nuevos proyectos de investigación científica.",
        [("712", "Generación de proyectos de investigación científica en ingeniería")],
    ),
    "Telemedicina y TIC para la salud materno-infantil amazónica": (
        "Despliegue de redes de telecomunicaciones para mejorar la atención de salud materno-infantil en zonas amazónicas remotas.",
        [("333", "Telemedicina para la salud materno-infantil en la cuenca del río Napo")],
    ),
    "Monitoreo de contaminación atmosférica industrial en Lima": (
        "Seguimiento de indicadores de contaminación atmosférica generados por procesos de combustión industrial en Lima.",
        [("357", "Partículas carbonosas esferoidales como indicador de contaminación atmosférica industrial en Lima")],
    ),
    "Diagnóstico termográfico de enfermedades crónicas": (
        "Desarrollo de procedimientos clínicos no invasivos basados en imágenes termográficas para el diagnóstico preventivo.",
        [("433", "Diagnóstico termográfico preventivo del pie diabético")],
    ),
    "Valorización energética y puzolánica de residuos agrícolas": (
        "Aprovechamiento integrado de residuos agrícolas para producir energía y materiales puzolánicos.",
        [("366", "Aprovechamiento integral de hojas de caña de azúcar en energía y material puzolánico")],
    ),
    "Nanogeneradores triboeléctricos biodegradables": (
        "Fabricación de nanogeneradores triboeléctricos biodegradables a partir de biopolímeros de recursos renovables.",
        [("905", "Nanogenerador triboeléctrico biodegradable a partir de almidón de papa andina")],
    ),
    "Combustión dual diésel-gas natural en motores de aplicación vehicular": (
        "Evaluación experimental de la sustitución parcial de diésel por gas natural en motores de combustión.",
        [("604", "Sustitución parcial de diésel por gas natural en motores de combustión a nivel del mar")],
    ),
    "Recubrimientos nanoestructurados por fricción-agitación en aleaciones metálicas": (
        "Desarrollo de recubrimientos superficiales nanoestructurados mediante procesos de fricción-agitación en aleaciones metálicas.",
        [("79", "Recubrimientos nanoestructurados en aluminio por fricción-agitación (FSP)")],
    ),
    "Trazabilidad ganadera mediante RFID": (
        "Sistemas de identificación y gestión de información para la trazabilidad del ganado mediante tecnología RFID.",
        [("49", "Sistema de trazabilidad de ganado vacuno con RFID y gestión web")],
    ),
    "Aditivos alimentarios funcionales a partir de subproductos vegetales andinos": (
        "Desarrollo de aditivos alimentarios funcionales a partir de subproductos y residuos de cultivos vegetales andinos.",
        [("633", "Mucílago atomizado de Sanky como aditivo alimentario funcional")],
    ),
    "Comunidades estudiantiles de investigación e innovación": (
        "Iniciativas estudiantiles que promueven la construcción colectiva de investigación e innovación con impacto social.",
        [("923", "Comunica Investiga Lab: comunidad estudiantil de investigación en comunicaciones")],
    ),
    "Teatro histórico sobre la Guerra del Pacífico": (
        "Producciones de dramaturgia peruana que abordan episodios históricos de la Guerra del Pacífico.",
        [("109", "Drama histórico sobre Bolognesi en la Guerra del Pacífico")],
    ),
    "Estereotipos, prejuicio intergrupal e identidad nacional": (
        "Estudio de las percepciones estereotípicas, el prejuicio intergrupal y su relación con la construcción de identidades regionales y nacionales.",
        [("596", "Estereotipos, prejuicio intergrupal e identidades regionales entre Lima y Huamanga")],
    ),
    "Neurociencia cognitiva aplicada a la educación": (
        "Exploración de los aportes de la neurociencia a la comprensión del aprendizaje y la cognición en contextos educativos.",
        [("252", "Neurociencia aplicada al aprendizaje y la cognición")],
    ),
    "Legado psicosocial de megaeventos deportivos": (
        "Análisis del impacto psicosocial e identitario de megaeventos deportivos y sus proyectos de legado.",
        [("910", "Impacto psicosocial e identitario del legado de los Juegos Panamericanos Lima 2019")],
    ),
    "Sentido de comunidad y bienestar en contextos de pobreza urbana": (
        "Estudio de las relaciones entre sentido de comunidad, participación y bienestar en contextos de pobreza urbana.",
        [("321", "Sentido de comunidad y bienestar en asentamientos humanos limeños")],
    ),
    "Neurocognición de la interacción humano-robot": (
        "Estudio neurocognitivo de la percepción de acciones y emociones en la interacción entre humanos y robots humanoides.",
        [("719", "Neurocognición de la percepción de emociones en la interacción humano-robot")],
    ),
    "Desarrollo cognitivo y moral intercultural en adolescentes indígenas": (
        "Exploración del desarrollo de operaciones lógicas y juicio moral en adolescentes de comunidades indígenas peruanas.",
        [("402", "Desarrollo cognitivo y juicio moral en adolescentes shipibo y quechua")],
    ),
    "Antropología visual y cultural en contextos posconflicto": (
        "Desarrollo de capacidades de investigación en antropología visual y cultural en contextos de posconflicto.",
        [("861", "Creación de capacidades en antropología visual y cultural postconflicto")],
    ),
    "Transversalización de género en proyectos de desarrollo rural": (
        "Incorporación de la perspectiva de equidad de género en proyectos de mejora de condiciones de vida rural.",
        [("48", "Transversalización de género en el proyecto PROPOMAC en Lambayeque")],
    ),
    "Segmentación y movilidad del mercado laboral peruano": (
        "Análisis de la segmentación del mercado laboral peruano, sus diferenciales de ingresos y la movilidad entre segmentos.",
        [("226", "Segmentación del mercado laboral peruano: diferenciales de ingresos y movilidad")],
    ),
    "Comercio internacional e integración regional Asia-Pacífico": (
        "Análisis de los desafíos y trayectorias de integración comercial del Perú y América Latina frente a Asia-Pacífico.",
        [("610", "El Perú frente al Acuerdo Transpacífico (TPP) y la integración Asia-Pacífico")],
    ),
    "Constitucionalismo y derecho público peruano contemporáneo": (
        "Reflexión sobre los desafíos del constitucionalismo y el derecho público en el Perú contemporáneo.",
        [("144", "Desafíos del constitucionalismo peruano del siglo XXI")],
    ),
    "Metodología de valoración racional de la prueba pericial": (
        "Desarrollo de metodologías y criterios para el análisis racional y control intersubjetivo de la prueba pericial en procesos judiciales.",
        [("280", "Metodología racional para el análisis y valoración de la prueba pericial")],
    ),
    "Filosofía del interculturalismo y multiculturalismo educativo": (
        "Análisis comparado de los fundamentos filosóficos y las políticas del multiculturalismo e interculturalismo en la educación latinoamericana.",
        [("283", "Fundamentos filosóficos del interculturalismo y multiculturalismo educativo latinoamericano")],
    ),
    "Historia cultural de las emociones políticas en el Perú posbélico": (
        "Estudio histórico-cultural de la política de las emociones entre los intelectuales del Perú posbélico.",
        [("651", "Política de las emociones entre los intelectuales del Perú posbélico")],
    ),
    "Historia del APRA y los partidos políticos peruanos del siglo XX": (
        "Análisis histórico de la construcción ideológica y partidaria de organizaciones políticas peruanas del siglo XX.",
        [("783", "Construcción ideológica y partidaria del APRA (1928-1930)")],
    ),
    "Latín colonial y formación humanística de peruanistas": (
        "Elaboración de materiales de formación en latín orientados a la investigación de temas históricos peruanos.",
        [("320", "Curso de latín orientado a peruanistas")],
    ),
    "Evaluación de políticas públicas para el sector artesanal": (
        "Evaluación ex-post de los impactos y limitaciones de políticas públicas orientadas al desarrollo del sector artesanal.",
        [("785", "Evaluación ex-post de la Ley del Artesano (Ley 29073)")],
    ),
    "Investigación-creación artística sobre paisajes amazónicos": (
        "Procesos de investigación-creación artística a partir del trabajo de campo en paisajes y ecosistemas amazónicos.",
        [("803", "Espíritu del bosque: investigación-creación artística en la Amazonía de Pucallpa")],
    ),
    "Redes académicas de derechos humanos en la educación superior": (
        "Redes académicas orientadas a mejorar la calidad y accesibilidad de la educación superior en derechos humanos.",
        [("311", "Red ALFA-DHES de derechos humanos en la educación superior latinoamericana")],
    ),
    "Migración circular y adaptación familiar al cambio ambiental rural": (
        "Estudio de estrategias de movilidad familiar (multirresidencia, migración circular) como adaptación al deterioro ambiental en zonas rurales.",
        [("587", "Multirresidencia y migración circular como adaptación familiar al deterioro ambiental")],
    ),
    "Lenguaje judicial claro y acceso a la justicia": (
        "Estudio del lenguaje judicial escrito y las barreras que enfrenta su comprensión por parte de poblaciones vulnerables.",
        [("730", "Lenguaje judicial claro y acceso a la justicia en procesos de familia")],
    ),
    "Ciudadanía intercultural y acción afirmativa en la educación superior": (
        "Promoción del ejercicio de la ciudadanía intercultural y acompañamiento a programas de acción afirmativa en universidades.",
        [("230", "Ciudadanía intercultural y acción afirmativa en la educación superior")],
    ),
    "Historiografía y teoría de la historia latinoamericana": (
        "Reflexión sobre la historiografía y la teoría de la historia en la producción académica latinoamericana.",
        [("276", "Historiografía y teoría de la historia en América Latina")],
    ),
    "Investigación-creación en danza y percepción corporal": (
        "Procesos de investigación-creación en danza que exploran el cuerpo, el contacto y la percepción.",
        [("930", "PosTacto: investigación-creación en danza sobre el contacto post-pandemia")],
    ),
}
