# -*- coding: utf-8 -*-
"""EXTRACTED topics for batch01 (60 projects, sanity-check batch beyond the
36-project pilot) — see docs/topic_normalization_pipeline.md and
build_pilot_topics_data.py for the methodology and file structure this
mirrors. Consumed by build_topics_data.py, which merges this with the pilot
and assigns/extends normalized topics; this file only holds the per-project
extraction (source of truth for what was read out of each project's text).
"""

# project_id -> list of (topic, description, evidence, confidence)
EXTRACTED_BATCH01 = {
"464": [
    ("Mejora de vivienda vernácula altoandina con eficiencia térmica",
     "Metodología de intervención de viviendas existentes en el hábitat altoandino de Puno, mejorando confort térmico, ventilación y seguridad mediante componentes constructivos y energías renovables locales.",
     "estudio, diseño, puesta en obra y validación de una metodología de intervención de viviendas existentes a través de la mejora de los componentes constructivos que influyen en los aspectos de seguridad y confort", 0.95),
    ("Rescate de técnicas constructivas vernáculas y tecnología apropiada",
     "Articulación de técnicas constructivas tradicionales campesinas con nuevas tecnologías investigadas en la PUCP para un modelo replicable y sostenible.",
     "se propondrán materiales locales y técnicas vernáculas asociados a nuevas tecnologías investigadas en la PUCP... generar un modelo replicable que cumpla con los criterios básicos de la sostenibilidad", 0.9),
],
"127": [
    ("Monitoreo participativo de calidad de agua en contexto minero",
     "Programa de monitoreo comunitario de calidad del agua vinculado a una operación minera, orientado a la gestión responsable de recursos hídricos.",
     "Monitoreo participativo; Calidad del agua; Minería responsable; Gestión comunitaria", 0.65),
],
"462": [
    ("Construcción explícita de soluciones de ecuaciones mediante cuerpos valorados",
     "Introduce la noción de cuerpo valorado y desarrollo en serie para construir algoritmos de resolución de ecuaciones algebraicas, diferenciales y en diferencias.",
     "introducir la noción de cuerpo valorado para construir algoritmos de resolución de ecuaciones con coeficientes en dicho cuerpo", 0.94),
    ("Escuelas doctorales internacionales de matemáticas PUCP",
     "Escuelas doctorales intercontinentales de Matemáticas PUCP-UVA y la iniciativa Matemáticas de la PUCP al Perú, promovidas por el investigador principal.",
     "la formación de investigadores a través de las Escuelas doctorales intercontinentales de Matemáticas PUCP UVA y de la iniciativa Matemáticas de la PUCP al Perú", 0.85),
],
"187": [
    ("Técnicas de manufactura óptica para superficies de telescopios",
     "Desarrollo de técnicas de multibloqueo para trabajar simultáneamente múltiples elementos ópticos, acelerando y mejorando la calidad del pulido de superficies para telescopios reflectores.",
     "técnicas de multibloqueo, mediante las cuales se trabaja simultáneamente diferentes elementos ópticos... Estas técnicas además de acortar de forma significativa el tiempo de los procesos, mejora la calidad obtenida de las superficies pulidas", 0.93),
    ("Digitalización de instrumentos de medición óptica de precisión",
     "Digitalización del esferómetro y aplicación de la prueba de Ronchi cuantitativa mediante procesamiento de imágenes para medir con precisión el radio de curvatura de superficies pulidas.",
     "se plantea la posibilidad de hacer la prueba de Ronchi cuantitativa en cuanto a determinar el error en la figura de la superficie pulida a partir de imágenes digitales", 0.88),
],
"161": [
    ("Compuestos bioactivos del maíz morado con actividad antioxidante",
     "Obtención de extractos de maíz morado ricos en antocianinas y bioflavonoides con actividad antioxidante y potencial quimiopreventivo.",
     "obtener extractos enriquecidos en antocianinas y bioflavonoides del maíz morado con probada actividad biológica", 0.95),
    ("Escalamiento industrial de nutracéuticos de origen vegetal",
     "Diseño de un proceso escalable industrialmente para producir nutracéuticos de alto valor comercial a partir del maíz morado.",
     "Se diseñará un proceso que permita escalarlos industrialmente. El éxito del proyecto requiere de la sinergia del trabajo químico y de las pruebas biológicas", 0.85),
],
"789": [
    ("Física experimental de altas energías en ALICE y MINERvA",
     "Desarrollo y caracterización de detectores para los experimentos ALICE (LHC) y MINERvA (Fermilab), estudiando producción de quarks pesados y señales de dileptones.",
     "nuestro trabajo se centrará en los experimentos ALICE (LHC) y MINERvA (Fermilab)... caracterizar los pAlpide, chips semiconductores que son los elementos activos de detección del MFT", 0.95),
    ("Física teórica de neutrinos: decoherencia cuántica y violación de CPT",
     "Estudios teóricos sobre decoherencia cuántica en oscilaciones de neutrinos y su impacto en la sensibilidad del experimento DUNE para observar violación de CPT.",
     "TESTING QUANTUM DECOHERENCE AT DUNE... PROBING CPT BREAKING INDUCED BY QUANTUM DECOHERENCE AT DUNE", 0.9),
],
"251": [
    ("Optimización de manufactura de películas delgadas ópticas",
     "Optimización del sistema de control del crecimiento de películas delgadas por evaporación térmica en alto vacío para aplicaciones ópticas.",
     "optimizar los elementos del sistema de control de un sistema de crecimiento de películas delgadas por el método de evaporación térmica en alto vacío para su aplicación en películas delgadas ópticas", 0.93),
],
"560": [
    ("H-cuerpos y formas diferenciales en la resolución de ecuaciones",
     "Extensión de la noción de cuerpo valorado a H-cuerpos (cuerpos de Hardy) estables por derivación, buscando contrapartidas algebraicas a resultados de Fortuny y Rosenlicht.",
     "utilizar las nociones de cuerpo valorado y H-cuerpos (noción algebraica de los cuerpos de Hardy), modificándola para hacerla estable por paso a la forma diferencial asociada a una derivada", 0.93),
    ("Escuelas doctorales internacionales de matemáticas y formación de investigadores",
     "Continuación de la formación de investigadores mediante la Escuela Doctoral Intercontinental PUCP-UVA (octava edición) y la Iniciativa Matemáticas de la PUCP al Perú.",
     "la formación de investigadores a través de las Escuelas doctorales intercontinentales de Matemáticas PUCP UVA (octava edición)... auspiciada por el CIMPA", 0.85),
],
"373": [
    ("Fenómeno de condensación en procesos estocásticos de partículas",
     "Estudio del proceso de rango cero y el fenómeno de condensación, donde las partículas se concentran en un solo sitio en volumen finito.",
     "ocurre un fenómeno que en la literatura física es llamado condensación... las partículas se concentran en un sólo sitio", 0.92),
    ("Escalas temporales de nucleación en la condensación de partículas",
     "Determinación de la escala de tiempo N^2 en la que ocurre la nucleación, es decir, la trayectoria seguida hasta que se origina el condensado de partículas.",
     "Nuestro objetivo es probar que la nucleación ocurre en la escala de tiempo N^2", 0.9),
],
"407": [
    ("Caracterización química de pigmentos en pintura virreinal",
     "Metodología de análisis por cromatografía de gases-espectrometría de masas y fluorescencia de rayos X para caracterizar materiales orgánicos y pigmentos de las escuelas limeña y cuzqueña.",
     "implementar en nuestra universidad una metodología para el análisis de los componentes orgánicos en pinturas por medio de la cromatografía de gases acoplada a espectrometría de masas (GC/MS)", 0.94),
    ("Conservación de patrimonio pictórico colonial peruano",
     "Comprensión de la composición química de las pinturas virreinales como base para estrategias de conservación en el tiempo.",
     "una mejor comprensión de la composición química de una pintura contribuye... también es de gran ayuda en el diseño de estrategias que permitan su conservación", 0.85),
],
"454": [
    ("Formas normales de campos logarítmicos en geometría algebraica",
     "Investigación de formas normales de campos logarítmicos de curvas no casi-homogéneas mediante coordenadas analíticas.",
     "investigaremos las posibles formas normales de los campos logaritmos de curvas que no son casi homogéneos... hallaremos coordenadas analíticas", 0.9),
],
"499": [
    ("Dinámica de frentes de reacción-difusión con tensión superficial",
     "Estudio numérico de la propagación de frentes químicos considerando efectos de expansión térmica, tensión superficial y difusión molecular usando las ecuaciones eikonal y Kuramoto-Sivashinsky.",
     "nos enfocaremos en la interacción de mecanismos de propagacion de frentes de reacción que interactúan... tensión superficial, generación de calor, y difusión molecular", 0.93),
    ("Inestabilidades inducidas por flujo en frentes químicos",
     "Análisis de cómo el flujo de Poiseuille y Couette modifican la estabilidad y forma de los frentes de reacción caóticos y oscilatorios.",
     "STABILITY OF KURAMOTO-SIVASHINSKY FRONTS IN MOVING FLUID... the instability depends on which substance is advected", 0.87),
],
"380": [
    ("Evaluación de logros de aprendizaje en estadística y probabilidad escolar",
     "Medición del avance del conocimiento estadístico y probabilístico en estudiantes de primaria y secundaria frente a los Mapas de Progreso del Aprendizaje del IPEBA.",
     "conocer el avance del conocimiento en Estadística de los alumnos del ciclo 4... y el avance del conocimiento en Estadística y Probabilidad de los alumnos del ciclo 6", 0.94),
    ("Diseño de instrumentos de medición educativa estandarizados",
     "Confección y validación de instrumentos de medición alineados a los Mapas de Progreso, aplicados en una muestra de colegios de Lima.",
     "se procederá a la confección de los instrumentos de medición, validándolos antes de su aplicación", 0.85),
],
"634": [
    ("Sensores basados en nanopartículas de oro para detección de mercurio y cianuro",
     "Desarrollo de sensores colorimétricos de dispersión Rayleigh de resonancia usando nanopartículas de oro para cuantificar mercurio(II) y cianuro en aguas contaminadas por minería aurífera ilegal.",
     "desarrollar un método de cuantificación sensible, selectivo y de bajo costo para estos contaminantes empleando nanopartículas de oro (AuNPs) como sensores", 0.95),
    ("Química analítica aplicada a la contaminación por minería ilegal",
     "Motivado por el empleo irresponsable de mercurio y cianuro en la minería aurífera ilegal peruana, busca métodos portátiles de análisis in situ.",
     "En el Perú, este es un problema especialmente importante debido al empleo irresponsable de estos químicos en la minería aurífera ilegal", 0.88),
],
"639": [
    ("Ciudadanía y política de reparaciones en el posconflicto en Ayacucho",
     "Investigación sobre derechos humanos y la política de reparaciones en Ayacucho, complementando dimensiones conceptuales de investigaciones previas en la zona.",
     "trabajos de investigación en torno a Ayacucho... complemento dimensiones conceptuales y analíticas a la investigación realizada en Ayacucho los dos últimos años", 0.85),
],
"825": [
    ("Policy feedback y trampas de reforma en pensiones y educación superior",
     "Explica por qué las políticas neoliberales de pensiones y educación superior en Perú (1990-2016) se volvieron resistentes al cambio mediante mecanismos de policy feedback y debilidad estatal.",
     "proponemos que fueron las mismas reformas neoliberales instauradas en los años noventa y los legados de debilidad estatal los que dieron lugar a mecanismos que sostienen las trampas", 0.95),
    ("Comparación de resistencia al cambio entre sistemas de pensiones y educación",
     "Analiza por qué el sector educación superior mostró cambios más sustantivos que pensiones, en función del poder de los actores involucrados.",
     "en el área de educación superior los cambios a la política fueron más sustantivos; en contraste con pensiones, donde han sido periféricos", 0.88),
],
"384": [
    ("Diversificación de la política exterior peruana en la Guerra Fría",
     "Analiza los factores históricos y teóricos que explican el giro hacia una política exterior peruana más independiente durante el gobierno de Velasco Alvarado.",
     "esta realidad cambió durante la Guerra Fría... la política exterior peruana se diversificó y trazó un curso más independiente, especialmente durante... el Gobierno Revolucionario de las Fuerzas armadas", 0.92),
],
"83": [
    ("Riesgo ambiental y conflicto social en minería andina",
     "Lecciones etnográficas sobre percepción cultural del riesgo ambiental minero en comunidades andinas peruanas.",
     "Riesgo ambiental; Minería; Conflicto social; Etnografía andina", 0.65),
],
"8": [
    ("Taller de metodología de investigación interdisciplinaria para docentes",
     "Taller de capacitación académica en metodología de investigación interdisciplinaria dirigido a docentes.",
     "Metodología de investigación; Interdisciplinariedad; Formación docente; Capacitación académica", 0.6),
],
"776": [
    ("Metodología de evaluación de eficiencia energética en sistemas neumáticos industriales",
     "Desarrollo de una metodología para analizar la eficiencia energética en sistemas neumáticos usados en la industria.",
     "Sistemas neumáticos; Eficiencia energética; Metodología de evaluación; Industria", 0.7),
],
"61": [
    ("Prototipo de termociclador de bajo costo para biotecnología",
     "Ensamble y fabricación de un prototipo de termociclador para réplica de ADN.",
     "Termociclador; Replicación de ADN; Prototipado; Biotecnología", 0.65),
],
"428": [
    ("Desarrollo institucional de ingeniería biomédica neonatal",
     "Fortalecimiento del área de ingeniería neonatal orientada a tecnología médica para la atención de recién nacidos.",
     "Ingeniería neonatal; Tecnología médica; Atención neonatal; Desarrollo institucional", 0.62),
],
"482": [
    ("Diagnóstico descentralizado de fallas en sistemas híbridos industriales",
     "Desarrollo de una metodología de diagnóstico de fallas para sistemas continuos-discretos (híbridos) que considere sus interacciones, con aplicación en plantas industriales y sistemas móviles.",
     "desarrollo de una metodología para el diagnóstico descentralizado de fallas en sistemas híbridos, que realice diagnósticos rápidos y efectivos, con mínima carga computacional", 0.94),
    ("Software de supervisión autónoma para procesos industriales",
     "Implementación práctica de las técnicas de diagnóstico en un software patentable, integrado a un sistema de control distribuido para uso en enseñanza e industria.",
     "se obtendrá un software de diagnóstico descentralizado de fallas aplicable a procesos industriales y sistemas móviles... El software será patentado", 0.85),
],
"405": [
    ("Valorización energética de residuos agroindustriales (hojas de caña)",
     "Producción de calor por combustión de hojas de caña de azúcar y transformación de cenizas en insumo puzolánico para la industria del cemento.",
     "el uso de las hojas de caña de azúcar (HCA)... para la producción de calor por combustión y la transformación de las cenizas calcinadas en un insumo para la fabricación de cemento", 0.94),
    ("Economía circular en la agroindustria azucarera",
     "Diagnóstico de residuos en ingenios azucareros para proponer soluciones de eliminación con bajas emisiones y valor industrial.",
     "se realizarán visitas a los ingenios azucareros... con la finalidad de conocer detalles del proceso productivo, volúmenes y usos que le dan a los residuos generados", 0.85),
],
"545": [
    ("Tecnologías de diagnóstico mejorado para tuberculosis",
     "Desarrollo de nuevas tecnologías de diagnóstico para tuberculosis, enfermedad endémica en el Perú con alta tasa de resistencia a fármacos.",
     "mientras que la tuberculosis (TBC) ha sido erradicada en países desarrollados, en el Perú, esta enfermedad es endémica... los casos de tuberculosis multidrogo resistente va en aumento", 0.93),
    ("Diagnóstico temprano de cáncer ginecológico en poblaciones vulnerables",
     "Desarrollo de tecnología para diagnóstico de cáncer cervical accesible a poblaciones sin acceso a controles rutinarios como el papanicolau.",
     "la población en general y las mujeres en sectores más empobrecidos no pueden acceder a estas revisiones rutinarias, lo que ha causado que este cáncer sea el responsable de más muertes", 0.9),
],
"677": [
    ("Evaluación estructural de patrimonio histórico religioso en Belén",
     "Evaluación preliminar de cimentaciones y muros históricos cruzados en el St. Jerome Hall de la Iglesia de la Natividad en Belén.",
     "PRELIMINARY STRUCTURAL AND FOUNDATION ASSESSMENT OF THE HISTORIC CRUSADER WALLS AND PILLARS AT THE ST. JEROME HALL... CHURCH OF THE NATIVITY, BETHLEHEM", 0.75),
],
"233": [
    ("Reforzamiento estructural de construcciones históricas de tierra",
     "Desarrollo de una técnica de reforzamiento compatible y reversible para complementar la reparación de grietas por inyección de barro líquido en muros de adobe históricos.",
     "desarrollar una técnica de reforzamiento estructural adicional para complementar la reparación de las fisuras por inyección de barro líquido en las grietas de los muros de adobe", 0.94),
    ("Resiliencia sísmica de patrimonio de tierra ante sismos",
     "Validación mediante ensayos de simulación sísmica de la eficacia del sistema combinado de reparación para evitar el colapso post-agrietamiento.",
     "La eficacia del sistema combinado (inyección de barro más refuerzos adicionales) será comprobada mediante ensayos de simulación sísmica", 0.87),
],
"814": [
    ("Caracterización biomédica de patrones respiratorios en tartamudez",
     "Análisis cuantitativo de patrones de respiración en personas con tartamudez durante diversas situaciones de habla, correlacionándolos con tipos de bloqueos.",
     "investigación de los parámetros variables en los patrones de respiración en personas con tartamudez (PCT) durante diversas situaciones de habla, con el objetivo de caracterizar dichos patrones", 0.94),
    ("Dispositivo de biofeedback para monitoreo de tartamudez",
     "Diseño conceptual de un dispositivo de monitoreo de patrones respiratorios que brinde feedback al paciente sobre la técnica de respiración controlada.",
     "se elaborará el diseño conceptual de un dispositivo para el monitoreo de la respiración y la identificación de bloqueos, que posibilite el feedback a la persona con tartamudez", 0.88),
],
"196": [
    ("Red birregional de transferencia tecnológica en cambio climático",
     "Cooperación entre centros de innovación de Europa y América Latina para la transferencia de tecnología en cambio climático.",
     "Transferencia tecnológica; Cambio climático; Cooperación birregional; Centros de innovación", 0.65),
],
"316": [
    ("Sistema automatizado de fabricación de asientos personalizados",
     "Desarrollo de un sistema que talla tridimensionalmente espuma de poliuretano según datos de presión, para fabricar asientos conformados para sillas de ruedas y prevenir escaras.",
     "el desarrollo de un sistema capaz de fabricar en forma automática asientos conformados en una matriz de espuma de poliuretano... para el tallado tridimensional de los asientos", 0.94),
    ("Tecnología asistiva de bajo costo para personas con discapacidad",
     "Automatización del proceso, antes manual, de tallado de asientos para reducir la formación de escaras en personas con discapacidad.",
     "permitiendo evitar el problema de formación de escaras en personas discapacitadas... el trabajo final no corresponde a lo que realmente requiere el paciente", 0.85),
],
"763": [
    ("Representaciones dispersas convolucionales para video 3D",
     "Algoritmo progresivo computacionalmente eficiente para representaciones sparse convolucionales aplicadas a datos tridimensionales (video digital).",
     "el desarrollo de un algoritmo progresivo computacionalmente eficiente para analizar vídeos digitales (data tri-dimensional) vía técnicas CSR", 0.93),
    ("Reconocimiento de actividades humanas en video mediante procesamiento disperso",
     "Aplicación de representaciones sparse para identificar acciones humanas relevantes en video, eliminando objetos estáticos del análisis.",
     "El reconocimiento de actividades humanas se orienta a la identificación de acciones que involucran movimiento... se plantea analizar el correspondiente video sparse", 0.87),
],
"565": [
    ("Gestión sostenible de activos industriales por costo total de propiedad",
     "Diseño y gestión sostenible de activos industriales evaluando el valor total y costo total de propiedad.",
     "Gestión de activos; Diseño sostenible; Costo total de propiedad; Valor industrial", 0.65),
],
"137": [
    ("Monitoreo de compuestos orgánicos volátiles biogénicos en dosel amazónico",
     "Sistema de monitoreo sensible de emisiones de BVOCs en el dosel del bosque amazónico de Tambopata como indicador temprano de cambios fisiológicos vegetales.",
     "modificar de manera significativa un sistema ya existente de monitoreo de los perfiles de emisión de BVOCs en bosque amazónico en la Reserva Nacional de Tambopata", 0.93),
    ("Ciclaje de carbono y cambio climático en bosques tropicales",
     "Vínculo entre la emisión de volátiles biogénicos y el ciclaje de carbono forestal como indicador de alteraciones climáticas globales y regionales.",
     "Una parte importante del ciclaje de carbono en bosque está asociada a la emisión de volátiles biogénicos (BVOCs) por las plantas... hasta un 40% del carbono fijado por la fotosíntesis puede ser reemitido", 0.85),
],
"32": [
    ("Bienestar psicológico transcultural en estudiantes universitarios",
     "Estudio transcultural de perspectiva temporal, estrés percibido, afrontamiento y perfeccionismo en estudiantes de Perú, EE.UU. y Costa Rica.",
     "Perspectiva temporal; Estrés percibido; Perfeccionismo; Bienestar universitario", 0.68),
],
"741": [
    ("Validación de escalas de resiliencia en grupos vulnerables del Perú",
     "Adaptación y validación psicométrica de un modelo multinivel de resiliencia (RSA) en líderes comunitarios y adolescentes de zonas empobrecidas de Lima.",
     "verify the psychometric accuracy and cultural relevance of verifiable indicators... We will focus on two vulnerable groups living in impoverished neighborhoods of Lima", 0.94),
    ("Mecanismos protectores frente a pobreza y exclusión",
     "Modelo de mecanismos protectores de resiliencia frente a condiciones de riesgo psicosocial que explican bienestar, liderazgo social y logro educativo.",
     "Protective mechanisms of resilience explain psychosocial well-being despite of persistent and harsh life-circumstances (e.g. poverty, war)", 0.87),
],
"19": [
    ("Representaciones sociales de la niñez en comunidades costeras",
     "Estudio de psicología comunitaria sobre representaciones sociales de la niñez en madres del distrito de Punta Negra.",
     "Representaciones Sociales; Niñez; Maternidad; Psicología Comunitaria", 0.62),
],
"846": [
    ("Actitudes psicosociales del Perú hacia países vecinos",
     "Analiza cómo dogmatismo, autoritarismo, nacionalismo y patriotismo predicen percepciones de cortesía, confianza y probabilidad de guerra hacia Ecuador, Colombia, Brasil, Bolivia y Chile.",
     "Las variables independientes no configuran un modelo predictor aceptable. Solo destacan individualmente el Autoritarismo de Derecha (RWA) como predictor de las percepciones de Probabilidad de Guerra con Chile", 0.88),
    ("Fundamentos psicosociales para una cultura de paz",
     "Recomendaciones de investigación y educación para la paz basadas en actitudes intergrupales de estudiantes peruanos hacia países limítrofes.",
     "se brindaron recomendaciones para el diseño de estrategias de Investigación y Educación para la Paz", 0.82),
],
"531": [
    ("Adaptación cultural del test de Rorschach en niños peruanos",
     "Identificación y comparación de Contenidos y Respuestas Populares del Rorschach en niños asháninkas y cusqueños de 6 a 9 años, aportando normas para la adaptación del test en Perú.",
     "identificar y comparar los Contenidos y las Respuestas Populares brindados al Psicodiagnóstico Rorschach por niños asháninkas y cusqueños de 6 a 9 años de edad", 0.94),
    ("Impacto del contexto cultural en la evaluación psicométrica infantil",
     "Riesgo de comparar erróneamente resultados psicométricos entre niños de contextos culturales distintos ante la ausencia de normas locales.",
     "en el Perú se carece de estudios sobre ambos códigos para la población de niños, por lo que se corre el riesgo de compararlos equivocadamente con niños que se han desarrollado en contextos culturales distintos", 0.86),
],
"135": [
    ("Equilibrio político en el Virreinato del Perú bajo los Austrias",
     "Estudio del gobierno del virrey Conde de Castellar y su destitución en 1678 para entender los mecanismos de equilibrio político colonial.",
     "estudiar los mecanismos de equilibrio político en el Perú colonial durante los Austrias, a través del estudio del gobierno del virrey Conde de Castellar, quien fuera depuesto por el rey en 1678", 0.93),
    ("Consolidación de élites de poder en América colonial",
     "Analiza la reforma del pacto colonial y la consolidación de élites americanas frente al debilitamiento del poder monárquico en el siglo XVII.",
     "La consolidación de las élites de poder americanas durante el siglo XVII fue un proceso paralelo al continuo debilitamiento del poder monárquico en Indias", 0.85),
],
"365": [
    ("Arqueología de fortificaciones mochicas tardías en Jequetepeque",
     "Estudio, mapeo y caracterización de Cerro Chepén y San Ildefonso, sitios fortificados que ilustran relaciones antagónicas entre formaciones políticas mochicas previas al colapso de la sociedad.",
     "dos sitios fortificados Mochica Tardíos que ilustran las relacione antagónicas entre las pequeñas formaciones políticas Mochicas que coexistían en el valle en el periodo previo al colapso de esta sociedad", 0.94),
    ("Formación de investigadores y desarrollo comunitario en arqueología de campo",
     "Componentes de formación de jóvenes investigadores y estrategias de desarrollo sostenible comunitario en el entorno del programa arqueológico.",
     "continuaremos con dos componentes importantes del programa: continuar con la formación de jóvenes investigadores y el contribuir con estrategias de desarrollo sostenible comunitario", 0.85),
],
"784": [
    ("Arte y memoria de la violencia política peruana (1980-2000)",
     "Estudio de doce obras culturales peruanas que hacen memoria de la violencia política post-CVR, analizando cinco formas en que el arte funciona políticamente.",
     "El libro estudia creaciones culturalels peruanas que tienen como intención recordar la violencia política de 1980-2000... sostengo que 'hacer memoria' es una manera central en que el arte intenta ser político", 0.93),
    ("Enfoques decoloniales y feministas en la memoria cultural",
     "Análisis de cómo las obras adoptan empatía hacia la víctima, indignación crítica y enfoques decoloniales o feministas para procesar la violencia.",
     "La cuarta es adoptando un enfoque decolonial o feminista. Y la quinta es acercándose a la figura del perpetrador", 0.83),
],
"887": [
    ("Edición crítica de fuentes periodísticas coloniales limeñas",
     "Transcripción, actualización ortográfica y publicación del 'Diario de noticias sobresalientes en Lima' (1706-1711), fuente clave para las relaciones políticas entre España y sus virreinatos.",
     "completar la edición del material que compone el Diario con la publicación del periodo correspondiente a los años de 1706 a 1711 a través de un trabajo de transcripción, actualización ortográfica y anotación del texto", 0.94),
    ("Circulación transatlántica de noticias en el mundo hispánico colonial",
     "Estudio de las redes de noticias, mercado editorial y circulación de impresos efímeros entre España y el Perú en los siglos XVI-XVIII.",
     "se discuten las redes de noticias, el mercado y taller editorial en Lima (1700-1711)... con énfasis en la circulación transatlántica entre España y el Perú", 0.87),
],
"574": [
    ("Caracterización química de cerámica funeraria mochica-cajamarca",
     "Análisis de pinturas y pastas cerámicas mochica y cajamarca de San José de Moro mediante fluorescencia de rayos X y espectrometría Raman para reconstruir dinámicas socioeconómicas de producción.",
     "resultados de la caracterización química y mineralógica, mediante fluorescencia de rayos X portátil (pXRF) y espectrometría Raman, de pinturas de un grupo de cerámicas mochica y cajamarca", 0.87),
],
"267": [
    ("Historia de la erradicación de la poliomielitis en el Perú",
     "Análisis de los factores de éxito de la campaña de erradicación de la polio en Perú (1991), en cooperación entre MINSA y agencias internacionales.",
     "Gracias al esfuerzo de los trabajadores de salud del MINSA y la asistencia técnica y financiera de agencias internacionales de cooperación... se logró la erradicación de la poliomielitis en 1991", 0.93),
    ("Salud pública en contexto de crisis política y conflicto armado",
     "Examina cómo la crisis político-social y el conflicto armado interno peruano de fines de los 80 impactaron la implementación de la campaña sanitaria.",
     "busca entender cómo impactó la crisis político social que vivía el Perú entre fines de la década de 1980 e inicios de la década de 1990, en la implementación de la campaña de erradicación", 0.85),
],
"710": [
    ("Teoría unificada de usos referenciales y predicativos del lenguaje",
     "Propone una teoría semántica que explique tanto los usos referenciales como predicativos de nombres propios y deícticos, apoyada en evidencia interlingüística y gramática generativa.",
     "construir y defender una teoría sobre el significado de términos singulares paradigmáticos tales como los nombres propios y los deícticos que dé cuenta tanto de sus usos referenciales como de sus usos no-referenciales o predicativos", 0.92),
],
"728": [
    ("Fenomenología y hermenéutica aplicadas a problemas contemporáneos",
     "Aplicación de perspectivas fenomenológicas y hermenéuticas a la inter/transdisciplinariedad académica y a la convivencia en la diversidad cultural.",
     "la aplicación de las perspectivas fenomenológica y hermenéutica en la tematización e interpretación filosófica de dos grandes temas contemporáneos: 1. la inter- y trans-disciplinariedad... 2. la posibilidad de la convivencia humana en medio de la diversidad cultural", 0.9),
    ("Crítica trascendental al naturalismo filosófico",
     "Confronta las críticas contemporáneas al naturalismo no reduccionista con la crítica husserliana trascendental, en el contexto de un cambio de paradigma postmecanicista.",
     "examinar si la crítica de los defensores de este naturalismo renovado está o no justificada, confrontando sus argumentos con el auténtico sentido de la crítica trascendental al naturalismo", 0.83),
],
"534": [
    ("Validación de escala de calidad de servicios educativos de primera infancia",
     "Construcción y validación a nivel nacional de una escala para evaluar la calidad de servicios educativos de la primera infancia, con apoyo de SINEACE y MINEDU.",
     "CONSTRUCCION DE UNA ESCALA PARA LOS SERVICIOS PUBLICOS Y VALIDACION A NIVEL NACIONAL CON APOYO DEL PERSONAL DE SINEACE Y DEL MINEDU", 0.78),
],
"325": [
    ("Capital digital y prácticas de nuevos medios en estudiantes universitarios",
     "Propone el concepto de capital digital como combinación de capital social/cultural y contexto académico que explica el uso diferenciado de TIC por estudiantes PUCP.",
     "los estudiantes hacen un uso diferenciado de la tecnología de información y comunicación en relación directa a lo que podríamos llamar su capital digital, es decir la combinación de capital social y cultural", 0.92),
],
"694": [
    ("Impacto de medios sociales en campañas presidenciales peruanas",
     "Estimación del impacto efectivo de los medios sociales en las elecciones presidenciales peruanas de 2016.",
     "Medios sociales; Elecciones presidenciales; Comunicación política; Perú", 0.68),
],
"261": [
    ("Fortalecimiento de capacidades de investigación en política laboral",
     "Desarrollo de un sistema de información laboral y espacios de diálogo Estado-academia para fortalecer la generación de evidencia sobre trabajo decente en Perú.",
     "contribuir con el fortalecimiento de las capacidades de generar información para el desarrollo de investigaciones y para las decisiones de política pública en el área laboral", 0.9),
    ("Formación de nuevas generaciones de economistas laborales",
     "Desarrollo de capacidades de investigación especialmente en jóvenes economistas especializados en temas laborales.",
     "aportar con el desarrollo de las capacidades de investigación especialmente de jóvenes generaciones de economistas especializados en temas en temas laborales", 0.82),
],
"831": [
    ("Brechas institucionales en la atención estatal a víctimas de violencia de género",
     "Identifica problemas de capacidad estatal, coordinación intersectorial y prejuicios de operadores de justicia que explican la brecha entre la legislación de violencia de género y la atención real en Villa El Salvador y Huamanga.",
     "tres causas principales para explicar la brecha existente entre lo que plantea la legislación peruana en materia de violencia contra las mujeres y la atención que reciben las mujeres víctimas", 0.94),
    ("Legados institucionales y reforma en política de género",
     "Evalúa avances normativos e institucionales frente a barreras persistentes en la respuesta estatal a la violencia de género.",
     "Si bien se han dado avances importantes, encontramos barreras considerables que dificultan una respuesta estatal adecuada para las mujeres que presentan denuncias", 0.85),
],
"425": [
    ("Cambio estructural regional limitado pese al crecimiento económico peruano",
     "Tres medidas de cambio estructural muestran que las regiones pobres del Perú no lograron diversificar su estructura productiva pese al crecimiento y reducción de pobreza 2002-2012.",
     "las tres medidas de 'cambio estructural' que aquí se presentan señalan que dicho cambio no ha sido significativo a nivel de regiones, particularmente para el grupo de regiones 'pobres'", 0.93),
    ("Informalidad laboral y productividad regional",
     "Analiza la persistencia de baja productividad e informalidad laboral como obstáculo al desarrollo económico regional pese a leves mejoras.",
     "se requiere 'cambios estructurales' en producción y actividades informales de baja productividad tal que la enorme disparidad de la productividad laboral entre regiones... desaparezca", 0.84),
],
"68": [
    ("Propuestas legislativas contra el lavado de activos en el Perú",
     "Análisis del fenómeno del lavado de activos y propuestas de reforma legislativa penal para su combate.",
     "Lavado de Activos; Derecho Penal; Política Criminal; Reforma Legislativa", 0.68),
],
"618": [
    ("Clasificación funcional de leyes para evaluar su efectividad normativa",
     "Propuesta de clasificación de leyes según su contenido y funciones como base para analizar la efectividad de la legislación en sede parlamentaria.",
     "CLASIFICACION FUNCIONAL DE LAS LEYES EN SEDE PARLAMENTARIA PARA EL ANALISIS DE SU EFECTIVIDAD LEGISLATIVA", 0.72),
],
"90": [
    ("Videoinstalación crítica sobre multiculturalismo y orientalismo",
     "Obra en artes visuales y ensayo teórico sobre los procesos de universalización cultural, abordando la interacción Occidente/Oriente a partir del conflicto EEUU-Irak.",
     "sistematización progresiva de los elementos constitutivos de una video-instalación para generar un comentario visual crítico... acerca de los procesos de universalización de la sociedad contemporánea", 0.88),
    ("Estudios postcoloniales y representación en el arte contemporáneo",
     "Análisis desde los estudios culturales y postcoloniales de cómo el arte islámico y símbolos hegemónicos occidentales se combinan en una instalación híbrida.",
     "La iconicidad de la palabra en el arte islámico, es disgregada por elementos de la cultura de masas, que a su vez parodian discursos hegemónicos representativos de la historia de la civilidad de la sociedad Occidental", 0.8),
],
"86": [
    ("Legitimación del Lugar de la Memoria mediante diálogo social",
     "Promoción del diálogo con actores sociales y políticos para legitimar un espacio dedicado a la memoria de la violencia sufrida en Perú entre 1980 y 2000.",
     "propiciar la legitimación del Lugar de la Memoria a través de la promoción del diálogo con diversos actores sociales y políticos", 0.9),
    ("Inclusión de todas las víctimas en las políticas de memoria",
     "Discusión sobre cómo el espacio de memoria debe incluir la visión de todos los afectados por el conflicto armado interno.",
     "se discutirá sobre las características que dicho espacio debería tener para incluir la visión de todos los afectados por el conflicto armado interno", 0.83),
],
"138": [
    ("Representación del adulto mayor en la publicidad peruana",
     "Análisis de los modelos e imágenes de personas adultas mayores en la publicidad peruana desde una perspectiva de edadismo.",
     "Personas adultas mayores; Publicidad peruana; Representación social; Edadismo", 0.68),
],
"578": [
    ("Modelamiento experimental de corrosividad de floculantes férricos",
     "Diseño experimental para determinar la concentración crítica de floculantes de sulfato y cloruro férrico y el material ferroso más adecuado para plantas de tratamiento de agua potable.",
     "DETERMINAR LA CONCENTRACION CRITICAS DE CADA FLOCULANTE DE ACUERDO AL TIPO DE MATERIAL... DETERMINAR EL MATERIAL FERROSO MAS ADECUADO PARA LOS SISTEMAS DE CLARIFICACION DE LAS PLANTAS DE TRATAMIENTO DE AGUA POTABLE", 0.82),
],
"595": [
    ("Adaptación indígena al cambio climático y contaminación en la Amazonía",
     "Estudio de percepciones y estrategias de adaptación de comunidades indígenas de Loreto y Junín frente al cambio climático y la contaminación de recursos hídricos.",
     "estudiar los impactos de los cambios ambientales en comunidades indígenas amazónicas, particularmente a partir del cambio climático y de la contaminación de los recursos hídricos... comprender mejor las percepciones y estrategias de adaptación", 0.94),
    ("Impacto de derrames petroleros en el territorio Kukama-Kukamiria",
     "Documentación de las transformaciones territoriales y sanitarias causadas por derrames de petróleo en comunidades indígenas de la cuenca baja del río Marañón.",
     "TRANSFORMACIONES EN EL TERRITORIO KUKAMA-KUKAMIRIA: IMPACTO DE LOS DERRAMES DE PETROLEO EN LAS COMUNIDADES INDIGENAS DE LA CUENCA BAJA DEL RIO MARAÑON", 0.87),
],
"396": [
    ("Gobernabilidad metropolitana ante la densificación urbana de Lima",
     "Examina cómo la gestión local y metropolitana enfrenta el desafío de la densificación urbana desigual y la creación de nuevas centralidades económicas en Lima.",
     "investigar si la gestión urbana facilita la integración de las centralidades con su entorno a través del tratamiento que recibe la densificación en sus planes y normativa", 0.93),
    ("Desigualdad territorial y nuevas centralidades económicas",
     "Analiza cómo la competencia entre distritos por atraer inversión genera bolsones residenciales de bajos ingresos alejados de oportunidades económicas.",
     "algunos gobiernos distritales tienden a competir entre ellos por atraer y concentrar estas centralidades, otros parecen quedar condenados a ser, sobretodo, bolsones residenciales de población de bajos ingresos", 0.85),
],
}

# --- Reuse: batch01 topics that clearly belong to an existing pilot topic ---
# (existing_normalized_topic_name, [(project_id, topic_text), ...])
REUSE_BATCH01 = [
("Materiales y sistemas constructivos sostenibles", [
    ("464", "Mejora de vivienda vernácula altoandina con eficiencia térmica"),
    ("464", "Rescate de técnicas constructivas vernáculas y tecnología apropiada"),
    ("405", "Valorización energética de residuos agroindustriales (hojas de caña)"),
    ("405", "Economía circular en la agroindustria azucarera"),
    ("233", "Reforzamiento estructural de construcciones históricas de tierra"),
    ("233", "Resiliencia sísmica de patrimonio de tierra ante sismos"),
]),
("Formación e innovación docente", [
    ("8", "Taller de metodología de investigación interdisciplinaria para docentes"),
]),
("Investigación y conservación del patrimonio arqueológico y arquitectónico", [
    ("677", "Evaluación estructural de patrimonio histórico religioso en Belén"),
    ("365", "Arqueología de fortificaciones mochicas tardías en Jequetepeque"),
    ("365", "Formación de investigadores y desarrollo comunitario en arqueología de campo"),
    ("574", "Caracterización química de cerámica funeraria mochica-cajamarca"),
]),
("Memoria histórica, género e identidad nacional", [
    ("784", "Arte y memoria de la violencia política peruana (1980-2000)"),
    ("784", "Enfoques decoloniales y feministas en la memoria cultural"),
    ("86", "Legitimación del Lugar de la Memoria mediante diálogo social"),
    ("86", "Inclusión de todas las víctimas en las políticas de memoria"),
]),
("Pueblos indígenas amazónicos: derechos, género y Estado", [
    ("595", "Adaptación indígena al cambio climático y contaminación en la Amazonía"),
    ("595", "Impacto de derrames petroleros en el territorio Kukama-Kukamiria"),
]),
("Sistema jurídico, derechos humanos y Estado de derecho", [
    ("68", "Propuestas legislativas contra el lavado de activos en el Perú"),
    ("618", "Clasificación funcional de leyes para evaluar su efectividad normativa"),
]),
("Cambio climático, recursos naturales y desarrollo sostenible", [
    ("196", "Red birregional de transferencia tecnológica en cambio climático"),
    ("137", "Monitoreo de compuestos orgánicos volátiles biogénicos en dosel amazónico"),
    ("137", "Ciclaje de carbono y cambio climático en bosques tropicales"),
]),
("Desigualdad económica y estructura social en el Perú", [
    ("425", "Cambio estructural regional limitado pese al crecimiento económico peruano"),
    ("425", "Informalidad laboral y productividad regional"),
]),
("Tecnologías digitales, TIC y desarrollo", [
    ("325", "Capital digital y prácticas de nuevos medios en estudiantes universitarios"),
]),
]

# --- New normalized topics (batch01 introduces subject areas not present in the pilot) ---
NEW_NORMALIZED_BATCH01 = {
"Minería, conflicto socioambiental y gestión del agua": (
    "Monitoreo de calidad de agua y percepción del riesgo ambiental en contextos de actividad minera en los Andes peruanos.",
    [("127", "Monitoreo participativo de calidad de agua en contexto minero"),
     ("83", "Riesgo ambiental y conflicto social en minería andina")],
),
"Álgebra y construcción explícita de soluciones de ecuaciones": (
    "Construcción algorítmica explícita de soluciones de ecuaciones algebraicas y diferenciales mediante la noción de cuerpo valorado y sus extensiones (H-cuerpos).",
    [("462", "Construcción explícita de soluciones de ecuaciones mediante cuerpos valorados"),
     ("560", "H-cuerpos y formas diferenciales en la resolución de ecuaciones")],
),
"Formación doctoral y cooperación académica internacional en matemáticas": (
    "Escuelas doctorales intercontinentales e iniciativas de cooperación PUCP con universidades europeas para la formación de investigadores en matemáticas.",
    [("462", "Escuelas doctorales internacionales de matemáticas PUCP"),
     ("560", "Escuelas doctorales internacionales de matemáticas y formación de investigadores")],
),
"Instrumentación y manufactura óptica de precisión": (
    "Técnicas y sistemas de control para la manufactura y medición de superficies y películas ópticas de precisión, aplicadas a telescopios e instrumentación científica.",
    [("187", "Técnicas de manufactura óptica para superficies de telescopios"),
     ("187", "Digitalización de instrumentos de medición óptica de precisión"),
     ("251", "Optimización de manufactura de películas delgadas ópticas")],
),
"Bioactivos naturales y nutracéuticos peruanos": (
    "Obtención y escalamiento industrial de compuestos bioactivos a partir de recursos vegetales nativos del Perú.",
    [("161", "Compuestos bioactivos del maíz morado con actividad antioxidante"),
     ("161", "Escalamiento industrial de nutracéuticos de origen vegetal")],
),
"Física experimental y teórica de altas energías": (
    "Investigación en física de partículas y astropartículas, combinando desarrollo de detectores para experimentos internacionales (ALICE, MINERvA) con modelos teóricos de neutrinos.",
    [("789", "Física experimental de altas energías en ALICE y MINERvA"),
     ("789", "Física teórica de neutrinos: decoherencia cuántica y violación de CPT")],
),
"Procesos estocásticos y teoría de probabilidad": (
    "Estudio matemático de fenómenos de condensación y nucleación en sistemas estocásticos de partículas.",
    [("373", "Fenómeno de condensación en procesos estocásticos de partículas"),
     ("373", "Escalas temporales de nucleación en la condensación de partículas")],
),
"Caracterización científica y conservación de patrimonio pictórico": (
    "Análisis químico y mineralógico de materiales orgánicos y pigmentos en pintura colonial para fines de conservación.",
    [("407", "Caracterización química de pigmentos en pintura virreinal"),
     ("407", "Conservación de patrimonio pictórico colonial peruano")],
),
"Geometría algebraica y teoría de singularidades": (
    "Estudio de formas normales de campos y objetos geométricos con singularidades en geometría algebraica compleja.",
    [("454", "Formas normales de campos logarítmicos en geometría algebraica")],
),
"Dinámica no lineal de frentes de reacción-difusión": (
    "Modelamiento numérico de la propagación e inestabilidad de frentes químicos bajo efectos de tensión superficial, calor y flujo de fluidos.",
    [("499", "Dinámica de frentes de reacción-difusión con tensión superficial"),
     ("499", "Inestabilidades inducidas por flujo en frentes químicos")],
),
"Evaluación y medición de la calidad educativa en el Perú": (
    "Diseño y validación de instrumentos para medir logros de aprendizaje y calidad de servicios educativos, desde educación básica hasta primera infancia.",
    [("380", "Evaluación de logros de aprendizaje en estadística y probabilidad escolar"),
     ("380", "Diseño de instrumentos de medición educativa estandarizados"),
     ("534", "Validación de escala de calidad de servicios educativos de primera infancia")],
),
"Nanosensores químicos para contaminación ambiental": (
    "Sensores basados en nanopartículas para la detección sensible de contaminantes químicos asociados a la minería ilegal.",
    [("634", "Sensores basados en nanopartículas de oro para detección de mercurio y cianuro"),
     ("634", "Química analítica aplicada a la contaminación por minería ilegal")],
),
"Memoria, reparaciones y ciudadanía en el posconflicto": (
    "Investigación sobre ciudadanía, derechos humanos y políticas de reparación en zonas afectadas por el conflicto armado interno.",
    [("639", "Ciudadanía y política de reparaciones en el posconflicto en Ayacucho")],
),
"Economía política de las reformas neoliberales en el Perú": (
    "Análisis de policy feedback y resistencia al cambio en las reformas neoliberales de pensiones y educación superior.",
    [("825", "Policy feedback y trampas de reforma en pensiones y educación superior"),
     ("825", "Comparación de resistencia al cambio entre sistemas de pensiones y educación")],
),
"Historia de la política exterior peruana": (
    "Análisis histórico de los factores que determinaron los giros de la política exterior del Perú en distintos periodos.",
    [("384", "Diversificación de la política exterior peruana en la Guerra Fría")],
),
"Eficiencia energética en sistemas industriales": (
    "Metodologías para evaluar y mejorar la eficiencia energética de sistemas y procesos industriales.",
    [("776", "Metodología de evaluación de eficiencia energética en sistemas neumáticos industriales")],
),
"Tecnología biomédica y asistiva desarrollada en el Perú": (
    "Prototipos de instrumentación biomédica y dispositivos asistivos de bajo costo desarrollados para necesidades locales de salud y discapacidad.",
    [("61", "Prototipo de termociclador de bajo costo para biotecnología"),
     ("428", "Desarrollo institucional de ingeniería biomédica neonatal"),
     ("814", "Dispositivo de biofeedback para monitoreo de tartamudez"),
     ("316", "Sistema automatizado de fabricación de asientos personalizados"),
     ("316", "Tecnología asistiva de bajo costo para personas con discapacidad")],
),
"Diagnóstico automático de fallas en sistemas industriales": (
    "Metodologías y software de diagnóstico descentralizado de fallas para sistemas híbridos en procesos industriales y móviles.",
    [("482", "Diagnóstico descentralizado de fallas en sistemas híbridos industriales"),
     ("482", "Software de supervisión autónoma para procesos industriales")],
),
"Diagnóstico clínico no invasivo y detección temprana de enfermedades": (
    "Desarrollo de tecnologías de diagnóstico accesible y no invasivo para enfermedades endémicas y trastornos del habla.",
    [("545", "Tecnologías de diagnóstico mejorado para tuberculosis"),
     ("545", "Diagnóstico temprano de cáncer ginecológico en poblaciones vulnerables"),
     ("814", "Caracterización biomédica de patrones respiratorios en tartamudez")],
),
"Procesamiento de señales y visión computacional": (
    "Algoritmos eficientes de representación dispersa aplicados al procesamiento de video para reconocimiento de actividades humanas.",
    [("763", "Representaciones dispersas convolucionales para video 3D"),
     ("763", "Reconocimiento de actividades humanas en video mediante procesamiento disperso")],
),
"Gestión sostenible de activos y organización industrial": (
    "Enfoques de gestión de activos industriales basados en el costo y valor total de propiedad.",
    [("565", "Gestión sostenible de activos industriales por costo total de propiedad")],
),
"Bienestar psicológico y estrés en estudiantes universitarios": (
    "Estudios transculturales sobre estrés percibido, afrontamiento y bienestar en poblaciones universitarias.",
    [("32", "Bienestar psicológico transcultural en estudiantes universitarios")],
),
"Resiliencia psicológica y mecanismos protectores en poblaciones vulnerables": (
    "Validación de modelos y escalas de resiliencia que explican el bienestar psicosocial pese a condiciones de pobreza o exclusión.",
    [("741", "Validación de escalas de resiliencia en grupos vulnerables del Perú"),
     ("741", "Mecanismos protectores frente a pobreza y exclusión")],
),
"Representaciones sociales y psicología comunitaria": (
    "Estudios de psicología comunitaria sobre representaciones sociales en poblaciones específicas.",
    [("19", "Representaciones sociales de la niñez en comunidades costeras")],
),
"Actitudes intergrupales, identidad nacional y cultura de paz": (
    "Estudio de actitudes psicosociales (autoritarismo, nacionalismo, patriotismo) hacia países vecinos y su relación con estrategias de cultura de paz.",
    [("846", "Actitudes psicosociales del Perú hacia países vecinos"),
     ("846", "Fundamentos psicosociales para una cultura de paz")],
),
"Adaptación transcultural de instrumentos psicométricos": (
    "Adaptación y validación de pruebas psicométricas (como el Rorschach) a poblaciones infantiles de distintos contextos culturales peruanos.",
    [("531", "Adaptación cultural del test de Rorschach en niños peruanos"),
     ("531", "Impacto del contexto cultural en la evaluación psicométrica infantil")],
),
"Historia política y social del Virreinato del Perú": (
    "Estudio de los mecanismos de equilibrio político y consolidación de élites de poder en el Perú colonial.",
    [("135", "Equilibrio político en el Virreinato del Perú bajo los Austrias"),
     ("135", "Consolidación de élites de poder en América colonial")],
),
"Fuentes históricas y circulación de información en el mundo hispánico colonial": (
    "Edición crítica y estudio de la circulación transatlántica de noticias impresas y manuscritas en el virreinato peruano.",
    [("887", "Edición crítica de fuentes periodísticas coloniales limeñas"),
     ("887", "Circulación transatlántica de noticias en el mundo hispánico colonial")],
),
"Historia de la salud pública y campañas sanitarias en el Perú": (
    "Análisis histórico de campañas sanitarias peruanas y su relación con el contexto político y social del país.",
    [("267", "Historia de la erradicación de la poliomielitis en el Perú"),
     ("267", "Salud pública en contexto de crisis política y conflicto armado")],
),
"Filosofía del lenguaje y semántica formal": (
    "Teorías semánticas sobre el significado de términos singulares del lenguaje natural.",
    [("710", "Teoría unificada de usos referenciales y predicativos del lenguaje")],
),
"Fenomenología, hermenéutica y filosofía contemporánea": (
    "Aplicación de métodos fenomenológicos y hermenéuticos a problemas filosóficos contemporáneos, incluyendo la crítica al naturalismo.",
    [("728", "Fenomenología y hermenéutica aplicadas a problemas contemporáneos"),
     ("728", "Crítica trascendental al naturalismo filosófico")],
),
"Comunicación política y medios digitales": (
    "Estimación del impacto de los medios sociales en procesos electorales y comunicación política.",
    [("694", "Impacto de medios sociales en campañas presidenciales peruanas")],
),
"Mercado laboral y políticas de trabajo decente": (
    "Fortalecimiento de capacidades de investigación y de sistemas de información para la política laboral peruana.",
    [("261", "Fortalecimiento de capacidades de investigación en política laboral"),
     ("261", "Formación de nuevas generaciones de economistas laborales")],
),
"Violencia de género y respuesta institucional del Estado": (
    "Análisis de las brechas entre la legislación de violencia de género y la capacidad real de respuesta institucional del Estado peruano.",
    [("831", "Brechas institucionales en la atención estatal a víctimas de violencia de género"),
     ("831", "Legados institucionales y reforma en política de género")],
),
"Arte contemporáneo, multiculturalismo y estudios postcoloniales": (
    "Obras de artes visuales que exploran el multiculturalismo global y el orientalismo desde una perspectiva postcolonial.",
    [("90", "Videoinstalación crítica sobre multiculturalismo y orientalismo"),
     ("90", "Estudios postcoloniales y representación en el arte contemporáneo")],
),
"Representación de grupos etarios en medios y publicidad": (
    "Análisis de cómo grupos etarios específicos, como el adulto mayor, son representados en la publicidad peruana.",
    [("138", "Representación del adulto mayor en la publicidad peruana")],
),
"Ingeniería de materiales para tratamiento de agua potable": (
    "Modelamiento experimental de la corrosividad de compuestos férricos y selección de materiales para plantas de tratamiento de agua potable.",
    [("578", "Modelamiento experimental de corrosividad de floculantes férricos")],
),
"Gobernanza urbana y desigualdad territorial en Lima": (
    "Análisis de cómo la gestión local y metropolitana enfrenta la densificación urbana desigual y la formación de nuevas centralidades económicas en Lima.",
    [("396", "Gobernabilidad metropolitana ante la densificación urbana de Lima"),
     ("396", "Desigualdad territorial y nuevas centralidades económicas")],
),
}
